### ISSUE TITLE
Spark fails to initialize when referencing Nessie Maven coordinates.

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#1222]
Spark fails with the following exception, when the Nessie-Delta-client is references via `spark.jars.packages`:
```
  conf.set(
    "spark.jars.packages",
    "org.projectnessie:nessie-deltalake-spark3:0.5.1")
```

```
21/05/11 18:41:29 ERROR SparkContext: Failed to add file:/home/snazy/.ivy2/jars/org.projectnessie_nessie-deltalake-core-0.5.1.jar to Spark environment
java.io.FileNotFoundException: Jar /home/snazy/.ivy2/jars/org.projectnessie_nessie-deltalake-core-0.5.1.jar not found
	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1848)
	at org.apache.spark.SparkContext.addJar(SparkContext.scala:1902)
	at org.apache.spark.SparkContext.$anonfun$new$11(SparkContext.scala:491)
	at org.apache.spark.SparkContext.$anonfun$new$11$adapted(SparkContext.scala:491)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:491)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Note: `nessie-deltalake-core` has the `source` classifier, there's no code in that Maven module.
Ivy itself correctly has the "right jar" (`org.projectnessie_nessie-deltalake-core-0.5.1-sources.jar`) in `~/.ivy2/jars`, but somehow Spark ignores the `source` classifier, tries to find the "normal" jar (which does not exist) and fails to start.

**Comment by snazy** [comment]
This might affect nessie-hms as well.

**Comment by snazy** [comment]
I think, we need to "clean-up" the pom packaged with the nessie-deltalake-spark2/3 shaded jars, because Spark still wants to resolve all dependences:
```
org.projectnessie#nessie-deltalake-spark3 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-bddc32a9-0823-45eb-8962-af0bd104fcd5;1.0
	confs: [default]
	found org.projectnessie#nessie-deltalake-spark3;0.5.2-SNAPSHOT in local-m2-cache
	found org.projectnessie#nessie-model;0.5.2-SNAPSHOT in local-m2-cache
	found com.google.code.findbugs#jsr305;3.0.2 in local-m2-cache
	found org.projectnessie#nessie-client;0.5.2-SNAPSHOT in local-m2-cache
	found io.delta#delta-core_2.12;0.8.0-nessie in local-m2-cache
	found org.antlr#antlr4;4.8 in local-m2-cache
	found org.antlr#antlr4-runtime;4.8 in local-m2-cache
	found org.antlr#antlr-runtime;3.5.2 in local-m2-cache
	found org.antlr#ST4;4.3 in local-m2-cache
	found org.abego.treelayout#org.abego.treelayout.core;1.0.3 in local-m2-cache
	found org.glassfish#javax.json;1.0.4 in local-m2-cache
	found com.ibm.icu#icu4j;61.1 in local-m2-cache
:: resolution report :: resolve 429ms :: artifacts dl 8ms
	:: modules in use:
	com.google.code.findbugs#jsr305;3.0.2 from local-m2-cache in [default]
	com.ibm.icu#icu4j;61.1 from local-m2-cache in [default]
	io.delta#delta-core_2.12;0.8.0-nessie from local-m2-cache in [default]
	org.abego.treelayout#org.abego.treelayout.core;1.0.3 from local-m2-cache in [default]
	org.antlr#ST4;4.3 from local-m2-cache in [default]
	org.antlr#antlr-runtime;3.5.2 from local-m2-cache in [default]
	org.antlr#antlr4;4.8 from local-m2-cache in [default]
	org.antlr#antlr4-runtime;4.8 from local-m2-cache in [default]
	org.glassfish#javax.json;1.0.4 from local-m2-cache in [default]
	org.projectnessie#nessie-client;0.5.2-SNAPSHOT from local-m2-cache in [default]
	org.projectnessie#nessie-deltalake-spark3;0.5.2-SNAPSHOT from local-m2-cache in [default]
	org.projectnessie#nessie-model;0.5.2-SNAPSHOT from local-m2-cache in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   12  |   0   |   0   |   0   ||   12  |   0   |
	---------------------------------------------------------------------
```
