### ISSUE TITLE
Python CLI: Showing Contents of DeltaLakeTable fails

### ISSUE THREAD

**Issue by nastra** [projectnessie/nessie#1462]
```
$ nessie contents -l
ICEBERG_TABLE:
  this.is.iceberg.foo
DELTA_LAKE_TABLE:
  this.is.delta.bar
```

```
$ nessie contents this.is.iceberg.foo
Iceberg table:
	/a/b/c
```
```
$ nessie contents this.is.delta.bar
Traceback (most recent call last):
  File "/home/nastra/Development/nessiepyenv/bin/nessie", line 33, in <module>
    sys.exit(load_entry_point('pynessie', 'console_scripts', 'nessie')())
  File "/home/nastra/Development/nessiepyenv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/nastra/Development/nessiepyenv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/nastra/Development/nessiepyenv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nastra/Development/nessiepyenv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nastra/Development/nessiepyenv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/nastra/Development/nessiepyenv/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/nastra/Development/nessiepyenv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/nastra/Development/workspace/nessie/python/pynessie/error.py", line 95, in wrapper
    f(*args, **kwargs)
  File "/home/nastra/Development/workspace/nessie/python/pynessie/cli.py", line 504, in contents
    results = ContentsSchema().dumps(content(*key), many=True) if ctx.json else "\n".join((i.pretty_print() for i in content(*key)))
  File "/home/nastra/Development/workspace/nessie/python/pynessie/cli.py", line 504, in <genexpr>
    results = ContentsSchema().dumps(content(*key), many=True) if ctx.json else "\n".join((i.pretty_print() for i in content(*key)))
  File "/home/nastra/Development/workspace/nessie/python/pynessie/nessie_client.py", line 145, in <genexpr>
    return (ContentsSchema().load(get_table(self._base_url, ref, _format_key(i), self._ssl_verify)) for i in tables)
  File "/home/nastra/Development/nessiepyenv/lib/python3.8/site-packages/marshmallow_oneofschema/one_of_schema.py", line 144, in load
    raise exc
marshmallow.exceptions.ValidationError: {'checkpointLocationHistory': ['Unknown field.'], 'metadataLocationHistory': ['Unknown field.'], 'lastCheckpoint': ['Unknown field.']}
```

**Comment by nastra** [comment]
Once #1451 is merged, I'll push a patch for this, as it currently depends on some changes (around testing) from #1451
