### ISSUE TITLE
CI flaky since #1777

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#1868]
CI for PRs + Ci for main are flaky.

From CI logs (in `:nessie-quarkus`):
```
Error:  Errors: 
Error:    TestBasicAuthentication.testValidAdminCredentials:43 » NessieInternalServer In...
Error:    TestBasicAuthentication.testValidCredentials:36 » NessieInternalServer Interna...
```

The preceding errors point to some internal error, probably related to Quarkus' test-profile w/ OIDC issue.

**Comment by dimas-b** [comment]
Related error from CI:
```
2021-08-30T16:04:30.9914714Z 2021-08-30 16:04:30,868 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /api/v1/trees failed, error id: 3bff7b63-6b38-476d-8b83-348cbe2bc74d-1: jav
a.lang.NullPointerException
2021-08-30T16:04:30.9918043Z    at io.quarkus.elytron.security.runtime.ElytronPasswordIdentityProvider$1.get(ElytronPasswordIdentityProvider.java:48)
2021-08-30T16:04:30.9921315Z    at io.quarkus.elytron.security.runtime.ElytronPasswordIdentityProvider$1.get(ElytronPasswordIdentityProvider.java:43)
2021-08-30T16:04:30.9924546Z    at io.quarkus.security.runtime.QuarkusIdentityProviderManagerImpl$1$1$1$1.run(QuarkusIdentityProviderManagerImpl.java:58)
2021-08-30T16:04:30.9927065Z    at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
2021-08-30T16:04:30.9928891Z    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2021-08-30T16:04:30.9930677Z    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2021-08-30T16:04:30.9932390Z    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2021-08-30T16:04:30.9935022Z    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2021-08-30T16:04:30.9937241Z    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-08-30T16:04:30.9938758Z    at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by dimas-b** [comment]
This CI error:
```
2021-08-30T16:04:31.6387453Z [ERROR] org.projectnessie.server.TestBasicAuthentication.testValidAdminCredentials  Time elapsed: 0.825 s  <<< ERROR!
2021-08-30T16:04:31.6389962Z org.projectnessie.client.rest.NessieInternalServerException: 
2021-08-30T16:04:31.6391279Z Internal Server Error (HTTP/500): Internal Server Error
2021-08-30T16:04:31.6393422Z com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "details" (class org.projectnessie.error.NessieError), not marked as ignorable (4 known properties: "serverStackTrace", "status", "reason", "message"])
```
Is a side effect of #1838

**Comment by snazy** [comment]
[Link for a failed run](https://github.com/projectnessie/nessie/pull/1693/checks?check_run_id=3463698824)

**Comment by dimas-b** [comment]
^ the link to the CI run points to the "latest" somehow, so the run that failed no longer shows up there (just for the same of clarify)

**Comment by dimas-b** [comment]
Possibly related message in CI logs:
```
2021-08-30T16:04:30.1620294Z 2021-08-30 16:04:27,519 WARN  [org.ecl.jet.ser.AbstractConnector] (pool-4-thread-1) Acceptors should be <= availableProcessors: NetworkTrafficServerConnector@6f324dcb{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
```
