### ISSUE TITLE
Test-bug: MongoDB Adapter test failure: AbstractTieredCommitsTest$Concurrency.concurrency

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#2026]
From CI log:
```
 [mongod output] 2021-09-16T22:24:42.610+0000 I NETWORK  [conn6] received client metadata from 127.0.0.1:57070 conn6: { driver: { name: "mongo-java-driver|sync", version: "4.3.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.8.0-1041-azure" }, platform: "Java/Azul Systems, Inc./11.0.12+7-LTS" }
[mongod output] 2021-09-16T22:24:42.622+0000 I NETWORK  [conn7] received client metadata from 127.0.0.1:57072 conn7: { driver: { name: "mongo-java-driver|sync", version: "4.3.1" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.8.0-1041-azure" }, platform: "Java/Azul Systems, Inc./11.0.12+7-LTS" }
[mongod output] AbstractTieredCommitsTest.concurrency - threads=4, singleBranch=false, sharedKeys=false, tables=3 : Commits OK: 85  Retry-Failures: 0
AbstractTieredCommitsTest.concurrency - threads=4, singleBranch=false, sharedKeys=true, tables=3 : Commits OK: 162  Retry-Failures: 0
AbstractTieredCommitsTest.concurrency - threads=4, singleBranch=true, sharedKeys=false, tables=3 : Commits OK: 132  Retry-Failures: 0
AbstractTieredCommitsTest.concurrency - threads=4, singleBranch=true, sharedKeys=true, tables=3 : Commits OK: 192  Retry-Failures: 0
Error:  Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.778 s <<< FAILURE! - in org.projectnessie.versioned.persist.tests.AbstractTieredCommitsTest$Concurrency
Error:  org.projectnessie.versioned.persist.tests.AbstractTieredCommitsTest$Concurrency.concurrency(Variation)[2]  Time elapsed: 1.663 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
[For branch BranchName{name=concurrency-0}] 
expected: [ContentsAndState{refState=<ByteString@9063080 size=0 contents="">, globalState=<ByteString@2f1d2384 size=2 contents="37">},
    ContentsAndState{refState=<ByteString@9063080 size=0 contents="">, globalState=<ByteString@50c20b15 size=2 contents="37">},
    ContentsAndState{refState=<ByteString@9063080 size=0 contents="">, globalState=<ByteString@6dcf39c6 size=2 contents="37">}]
 but was: [ContentsAndState{refState=<ByteString@9063080 size=0 contents="">, globalState=<ByteString@240b656f size=2 contents="34">},
    ContentsAndState{refState=<ByteString@9063080 size=0 contents="">, globalState=<ByteString@db610c3 size=2 contents="34">},
    ContentsAndState{refState=<ByteString@9063080 size=0 contents="">, globalState=<ByteString@254a9f65 size=2 contents="34">}]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at org.projectnessie.versioned.persist.tests.AbstractConcurrency.concurrency(AbstractConcurrency.java:268)
...
```

**Comment by snazy** [comment]
Hmmm... that's definitely a bug - maybe the CAS-operation isn't as safe as expected.
Not sure if it's related, but the output
```
AbstractTieredCommitsTest.concurrency - threads=4, singleBranch=*, sharedKeys=*, tables=3 : Commits OK: 162  Retry-Failures: 0
```
looks "interesting". I'd expect at least some retry-failures, but there are none. But maybe that's just because MongoDB isn't as fast as e.g. RocksDB.

**Comment by snazy** [comment]
Could also be a test-bug.

**Comment by snazy** [comment]
Strange. Cannot reproduce it locally even with 128 threads and >10s per variation.

**Comment by dimas-b** [comment]
Yeah, CI often has different behaviour so iffy stuff shows up in CI only :thinking:

**Comment by snazy** [comment]
Let that test repeat for ~1h30m on my machine. Still no luck w/ reproducing :(

**Comment by dimas-b** [comment]
There appears to be a race among test threads in this case (e.g. in `commitAndRecord(...)` between updating storage and updating internal maps)  that can cause spurious assertion failures.
