### ISSUE TITLE
GC test TestInstantConversion fails on Java 17

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#3945]
```
[ERROR] org.projectnessie.gc.base.TestInstantConversion.testInstantConversion  Time elapsed: 0.173 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: 2022-04-13T07:42:09.706331353Z
 but was: 2022-04-13T07:42:09.706331Z
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at org.projectnessie.gc.base.TestInstantConversion.testInstantConversion(TestInstantConversion.java:37)
```

**Comment by ajantha-bhat** [comment]
oh, Java 17 is giving nano second precision where as Java 11 gives micro second precision.

To add validation I should use `Math.floorMod` as in https://github.com/projectnessie/nessie/blob/main/gc/gc-base/src/main/java/org/projectnessie/gc/base/GCUtil.java#L64. 

But in that case no need of validation as both are using same code.

**I will remove this test case.**
