### ISSUE TITLE
Run command in spark-sql report error 'Connection refused'

### ISSUE THREAD

**Issue by wuleistarrocks** [projectnessie/nessie#4293]
**What happened**:

Run command in spark-sql report error 'Connection refused'

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
`spark-sql --packages "org.apache.iceberg:iceberg-spark-runtime-3.2_2.12:0.13.1,org.projectnessie:nessie-spark-3.2-extensions:0.30.0" \
--conf spark.sql.extensions="org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSpark32SessionExtensions" \
--conf spark.sql.catalog.nessie.catalog-impl=org.apache.iceberg.nessie.NessieCatalog \
--conf spark.sql.catalog.nessie.ref=main \
--conf spark.sql.catalog.nessie.uri=http://localhost:19120/api/v1 \
--conf spark.sql.catalog.nessie=org.apache.iceberg.spark.SparkCatalog \
--conf spark.sql.catalog.nessie.authentication.type=NONE \
--conf spark.sql.catalog.nessie.warehouse=/home/disk1/wulei/data_lake/nessie/data_warehouse`

Then I run command 'SHOW LOG in nessie' and some error happens, shows below:

`22/05/22 06:23:39 ERROR SparkSQLDriver: Failed in [SHOW LOG IN nessie]
org.projectnessie.client.http.HttpClientException: java.net.ConnectException: 拒绝连接 (Connection refused)
	at org.projectnessie.client.http.HttpRequest.executeRequest(HttpRequest.java:173)
	at org.projectnessie.client.http.HttpRequest.get(HttpRequest.java:183)
	at org.projectnessie.client.http.HttpTreeClient.getReferenceByName(HttpTreeClient.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.projectnessie.client.http.NessieHttpClient$ExceptionRewriter.invoke(NessieHttpClient.java:165)
	at com.sun.proxy.$Proxy22.getReferenceByName(Unknown Source)
	at org.projectnessie.client.http.v1api.HttpGetReference.get(HttpGetReference.java:46)
	at org.apache.spark.sql.execution.datasources.v2.NessieUtils$.getCurrentRef(NessieUtils.scala:245)
	` 

**Details**:
- Nessie server type (docker/built from source) and version: None
- Client type (Ex: UI/Spark/pynessie ...) and version: spark-sql version 3.2

**Comment by snazy** [comment]
Hi @wuleistarrocks , can you provide more details on what exactly happens and what has been setup and configured?
"Connection refused" is usually a network issue or misconfigured connection URL.

**Comment by nastra** [comment]
@wuleistarrocks can you do a `curl http://localhost:19120/api/v1/trees/tree` or is this failing as well? As @snazy mentioned this usually indicates a network issue (connection to nessie server running inside docker container not working, nessie server being down, ...)

**Comment by snazy** [comment]
Closing due to inactivity
