### ISSUE TITLE
java.lang.ClassNotFoundException: software.amazon.awssdk.services.s3.model.ObjectCannedACL

### ISSUE THREAD

**Issue by saimigo** [projectnessie/nessie#4447]
# Describe the bug
Missing dependencies in SDK class

# Current Behavior
when creating the NessieCatalog, the following exception is encountered

```
Exception in thread "main" java.lang.NoClassDefFoundError: software/amazon/awssdk/services/s3/model/ObjectCannedACL
	at org.apache.iceberg.aws.AwsProperties.<init>(AwsProperties.java:247)
	at org.apache.iceberg.aws.s3.S3FileIO.initialize(S3FileIO.java:104)
	at org.apache.iceberg.CatalogUtil.loadFileIO(CatalogUtil.java:268)
	at org.apache.iceberg.nessie.NessieCatalog.initialize(NessieCatalog.java:94)
	at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:193)
	at loshu.flink.iceberg.FlinkWriteIcebergTest.main(FlinkWriteIcebergTest.java:96)
Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.services.s3.model.ObjectCannedACL
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

Process finished with exit code 1
```
Part of dependencies in my pom.xml
```
       <dependency>
            <groupId>org.apache.iceberg</groupId>
            <artifactId>iceberg-nessie</artifactId>
            <version>${iceberg.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.iceberg</groupId>
            <artifactId>iceberg-aws</artifactId>
            <version>${iceberg.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/software.amazon.awssdk/s3 -->
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>bom</artifactId>
            <version>2.17.178</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>bundle</artifactId>
            <version>2.17.178</version>
        </dependency>

        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>url-connection-client</artifactId>
            <version>2.17.178</version>
        </dependency>
```

**Comment by persponal-wei** [comment]
My java code
```
    Map<String, String> properties = new HashMap<>();
    properties.put("type", "iceberg");
//    properties.put("catalog-impl", "org.apache.iceberg.nessie.NessieCatalog");
    properties.put("io-impl", "org.apache.iceberg.aws.s3.S3FileIO");
    properties.put("uri", "http://nessie:19120/api/v1");
    properties.put("ref", "main");
    properties.put("s3.endpoint", "https://mys3.com");
    properties.put("warehouse", "s3://warehouse/flink");

    Configuration conf = new Configuration();
    Catalog nessieCatalog = CatalogUtil.loadCatalog("org.apache.iceberg.nessie.NessieCatalog", "nessie", properties, conf);

```

**Comment by snazy** [comment]
This looks very much like an Iceberg issue, not a Nessie issue. Nessie itself does not interact with your object store, but Iceberg does.
Could you open an issue on the Iceberg side?

**Comment by snazy** [comment]
Actually, you should use the iceberg-spark3-runtime dependency

**Comment by persponal-wei** [comment]
> This looks very much like an Iceberg issue, not a Nessie issue. Nessie itself does not interact with your object store, but Iceberg does. Could you open an issue on the Iceberg side?

Ok，thanks！

**Comment by persponal-wei** [comment]
> @persponal-wei : Just wondering, why do you have a direct dependency on `software.amazon.awssdk:bom`? Should this rather by in the `dependencyManagement` section?

Because it says `software.amazon.awssdk:bom` not found. Just a test.

**Comment by persponal-wei** [comment]
> Actually, you should use the iceberg-spark3-runtime dependency

I use org.apache.iceberg:iceberg-flink dependency, not spark. 
Is there a problem with this dependency?

**Comment by snazy** [comment]
@saimigo it's not a Nessie issue, but a question about Iceberg w/ Flink + S3. Can you ask on the Iceberg mailing list or better Iceberg's slack at apache-iceberg.slack.com ?
