### ISSUE TITLE
How to set S3.endpoint in Java

### ISSUE THREAD

**Issue by saimigo** [projectnessie/nessie#4467]
# code

```
    Map<String, String> properties = new HashMap<>();
    properties.put("type", "iceberg");
//    properties.put("catalog-impl", "org.apache.iceberg.nessie.NessieCatalog");
    properties.put("io-impl", "org.apache.iceberg.aws.s3.S3FileIO");
    properties.put("uri", "http://nessie:19120/api/v1");
    properties.put("ref", "main");
    properties.put("s3.endpoint", "https://mys3.com");
    properties.put("warehouse", "s3://warehouse");

    Configuration conf = new Configuration();
    Catalog nessieCatalog = CatalogUtil.loadCatalog("org.apache.iceberg.nessie.NessieCatalog", "nessie", properties, conf);

```
I set `properties.put("s3.endpoint", "https://mys3.com");` It doesn't seem to take effect

# Exception
```
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: warehouse.s3.cn-north-2.amazonaws.com.cn
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:102)
	at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:204)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:83)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	... 25 more
Caused by: java.net.UnknownHostException: warehouse.s3.cn-north-2.amazonaws.com.cn
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.call(UrlConnectionHttpClient.java:283)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.call(UrlConnectionHttpClient.java:261)
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:77)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:56)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	... 37 more

Process finished with exit code 1
```

How to set s3 endpoint in Java code?

**Comment by ajantha-bhat** [comment]
@saimigo : 
NessieCatalog cannot understand S3 configurations if it is set in properties. 

Can you try passing them in Hadoop configuration[1]? You are already creating a fresh Hadoop configuration. So, you just need to set it in there like below.
```
Configuration conf = new Configuration();
conf.set("fs.s3a.endpoint", "https://mys3.com");
```

[1] https://hadoop.apache.org/docs/stable/hadoop-aws/tools/hadoop-aws/index.html

**Comment by ming12713** [comment]
> @saimigo : NessieCatalog cannot understand S3 configurations if it is set in properties.
> 
> Can you try passing them in Hadoop configuration[1]? You are already creating a fresh Hadoop configuration. So, you just need to set it in there like below.
> 
> ```
> Configuration conf = new Configuration();
> conf.set("fs.s3a.endpoint", "https://mys3.com");
> ```
> 
> [1] https://hadoop.apache.org/docs/stable/hadoop-aws/tools/hadoop-aws/index.html

@ajantha-bhat 
we use iceberg via nessice access minio object service,
use flink-sql create s3 catalog is ok..
`sql-client.sh embedded -j /jar/iceberg-flink-runtime-1.14-0.13.1.jar -j /jar/bundle-2.17.178.jar -j /jar/url-connection-client-2.17.178.jar shell`

`
Flink SQL> CREATE CATALOG s3_catalog WITH (
>   'type'='iceberg',
>   'catalog-impl'='org.apache.iceberg.nessie.NessieCatalog',
>   'io-impl'='org.apache.iceberg.aws.s3.S3FileIO',
>   'uri'='http://nessie:19120/api/v1',
>   'ref'='main',
>   's3.endpoint'='https://obs.uisee.com',
>   'warehouse'='s3://warehouse'
> );

use java sdk ,we can't found how to set minio endpoint as @saimigo  steps
`

**Comment by ajantha-bhat** [comment]
The method that I suggested above is not working?

**Comment by ming12713** [comment]
> The method that I suggested above is not working?
@ajantha-bhat 
create database and table is ok , flink sql default load s3 ak/sk/region from awscli profile 
![Screenshot from 2022-06-13 14-13-49](https://user-images.githubusercontent.com/5196113/173291409-3f361a35-50c7-4141-9d78-94df1b945ab4.png)

minio warehouse
![Screenshot from 2022-06-13 14-17-53](https://user-images.githubusercontent.com/5196113/173291528-2cd498d4-8300-4d13-b10e-ca60039c18bc.png)

**Comment by ming12713** [comment]
> # code
> ```
>     Map<String, String> properties = new HashMap<>();
>     properties.put("type", "iceberg");
> //    properties.put("catalog-impl", "org.apache.iceberg.nessie.NessieCatalog");
>     properties.put("io-impl", "org.apache.iceberg.aws.s3.S3FileIO");
>     properties.put("uri", "http://nessie:19120/api/v1");
>     properties.put("ref", "main");
>     properties.put("s3.endpoint", "https://mys3.com");
>     properties.put("warehouse", "s3://warehouse");
> 
>     Configuration conf = new Configuration();
>     Catalog nessieCatalog = CatalogUtil.loadCatalog("org.apache.iceberg.nessie.NessieCatalog", "nessie", properties, conf);
> ```
> 
> I set `properties.put("s3.endpoint", "https://mys3.com");` It doesn't seem to take effect
> 
> # Exception
> ```
> Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: warehouse.s3.cn-north-2.amazonaws.com.cn
> 	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:102)
> 	at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:204)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:83)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
> 	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
> 	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
> 	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
> 	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
> 	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
> 	... 25 more
**> Caused by: java.net.UnknownHostException: warehouse.s3.cn-north-2.amazonaws.com.cn**
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> 	at java.net.Socket.connect(Socket.java:589)
> 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
> 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
> 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
> 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
> 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
> 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
> 	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.call(UrlConnectionHttpClient.java:283)
> 	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.call(UrlConnectionHttpClient.java:261)
> 	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:64)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:77)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:56)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:39)
> 	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
> 	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
> 	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
> 	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
> 	... 37 more
> 
> Process finished with exit code 1
> ```
> 
> How to set s3 endpoint in Java code?

@ajantha-bhat 
`Caused by: java.net.UnknownHostException: warehouse.s3.cn-north-2.amazonaws.com.cn`
i think java client default load s3 config from aws profile ,because, **cn-north-2** is set in aws profile, host not found reaseon is cause by awscli not support endpoint in env profile

**Comment by snazy** [comment]
Closing due to inactivity.
