### ISSUE TITLE
`ClassCastException` when initializing HDFS-Spark

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#4774]
Some Hadoop libraries (HDFS stuff?) seem to "tweak" Java's mechanism to resolve URLs, so instead of resolving `http` to `HttpURLConnection`, it is resolved fo `org.apache.hadoop.fs.FsUrlConnection`, which leads to a `ClassCastException`.

The integration test in question is one that pulls in Spark, Flink, Presto, Iceberg and, of course, Nessie.

Not sure whether we have to tweak the Nessie client here to make it "resistant" against such things.

Frankly, our expectation that the cast-operation in question will always resolve to a `HttpURLConnection` is not great either.

Two issues at play here:
1. Hadoop code "hijacks" `http`, which feels wrong (there are implementations of `java.net.URLStreamHandler` in Hadoop code)
2. Nessie always expects the result of `URL.openConnection()` to be an instance of `java.net.HttpURLConnection`, which is strictly speaking wrong as well.

Since we cannot tweak (old and released) Hadoop code, the only solution here is to change the Nessie client code.

```
URI uri;
HttpURLConnection con = (HttpURLConnection) uri.toURL().openConnection();
```

```
java.lang.ClassCastException: class org.apache.hadoop.fs.FsUrlConnection cannot be cast to class java.net.HttpURLConnection (org.apache.hadoop.fs.FsUrlConnection is in unnamed module of loader 'app'; java.net.HttpURLConnection is in module java.base of loader 'bootstrap')
	at org.projectnessie.client.http.HttpRequest.executeRequest(HttpRequest.java:90)
	at org.projectnessie.client.http.HttpRequest.get(HttpRequest.java:188)
	at org.projectnessie.client.http.HttpTreeClient.getReferenceByName(HttpTreeClient.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.projectnessie.client.http.NessieHttpClient$ExceptionRewriter.invoke(NessieHttpClient.java:161)
	at com.sun.proxy.$Proxy18.getReferenceByName(Unknown Source)
	at org.projectnessie.client.http.v1api.HttpGetReference.get(HttpGetReference.java:47)
	at org.apache.iceberg.nessie.NessieIcebergClient.loadReference(NessieIcebergClient.java:100)
	at org.apache.iceberg.nessie.NessieIcebergClient.lambda$new$0(NessieIcebergClient.java:74)
	at org.apache.iceberg.relocated.com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at org.apache.iceberg.nessie.NessieIcebergClient.getRef(NessieIcebergClient.java:82)
	at org.apache.iceberg.nessie.NessieIcebergClient.refresh(NessieIcebergClient.java:86)
	at org.apache.iceberg.nessie.NessieTableOperations.doRefresh(NessieTableOperations.java:110)
	at org.apache.iceberg.BaseMetastoreTableOperations.refresh(BaseMetastoreTableOperations.java:96)
	at org.apache.iceberg.BaseMetastoreTableOperations.current(BaseMetastoreTableOperations.java:79)
	at org.apache.iceberg.BaseMetastoreCatalog.loadTable(BaseMetastoreCatalog.java:44)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at org.apache.iceberg.CachingCatalog.loadTable(CachingCatalog.java:161)
	at org.apache.iceberg.spark.SparkCatalog.load(SparkCatalog.java:556)
	at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:143)
	at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:100)
	at org.apache.spark.sql.connector.catalog.TableCatalog.tableExists(TableCatalog.java:156)
	at org.apache.spark.sql.execution.datasources.v2.CreateTableExec.run(CreateTableExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:560)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:220)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:622)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:617)
	at org.projectnessie.integtests.crossengine.ITCrossEngine.createTables(ITCrossEngine.java:48)

```

**Comment by snazy** [comment]
Hm. Seems this is caused by Spark and can be controlled via the configuration `spark.sql.defaultUrlStreamHandlerFactory.enabled`. See `org.apache.spark.sql.internal.SharedState#setFsUrlStreamHandlerFactory`

**Comment by snazy** [comment]
Once Nessie can at least use Java 11's new HTTP client with #4448 , the problem will not happen at all when using Java 11 or newer.
