### ISSUE TITLE
OIDC ConnectException on Nessie Server startup

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#5327]
```
$ docker run --rm -p 19120:19120 projectnessie/nessie:latest
 _   _               _         ____
| \ | |             (_)       / __ \
|  \| | ___  ___ ___ _  ___  / /__\/ ___ _ ____   _____ _ __
| . ` |/ _ \/ __/ __| |/ _ \ \___. \/ _ \ '__\ \ / / _ \ '__|
| |\  |  __/\__ \__ \ |  __/ /\__/ /  __/ |   \ V /  __/ |
\_| \_/\___||___/___/_|\___| \____/ \___|_|    \_/ \___|_|

                               https://projectnessie.org/

                              Powered by Quarkus 2.12.2.Final
2022-10-05 16:09:09,754 WARN  [io.qua.oid.com.run.OidcCommonUtils] (vert.x-eventloop-thread-1) OIDC Server is not available:: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.255.0.0:0
Caused by: java.net.ConnectException: Connection refused
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_ConnectException_constructor_026ed3e065cc052585fca43de83265b2d1381f28(JNIJavaCallWrappers.java:0)
	at sun.nio.ch.Net.pollConnect(Net.java)
	at sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
```

```
$ docker images
REPOSITORY                                 TAG               IMAGE ID       CREATED         SIZE
projectnessie/nessie                       latest            e2fbcf2e77ac   2 weeks ago     172MB
```

**Comment by dimas-b** [comment]
For background: the default `127.255.0.0` address was initially added to avoid startup failure because OIDC address had to be configured. 

Might be worth checking if it can be left blank when not in use.

**Comment by snazy** [comment]
I suspect, there's nothing we can do about this, closing for now
