### ISSUE TITLE
Nessie-Runner Jar

### ISSUE THREAD

**Issue by asheeshgarg** [projectnessie/nessie#5357]
I downloaded the nessie-quarkus-0.43.0.jar from maven central. Do we have a separate upload for the runner jar I dont see it on the maven central.

**What happened**:
java -jar nessie-quarkus-0.43.0.jar
no main manifest attribute, in nessie-quarkus-0.43.0.jar
**What you expected to happen**:
Start the server
**How to reproduce it (as minimally and precisely as possible)**:

**Details**:
- Nessie server type (docker/built from source) and version:
- Client type (Ex: UI/Spark/pynessie ...) and version:

**Comment by dimas-b** [comment]
@asheeshgarg : Did you mean to use `nessie-quarkus-0.43.0-runner.jar` perhaps? That one does start a Nessie Server:

```
$ java -jar nessie-quarkus-0.43.0-runner.jar
 _   _               _         ____
| \ | |             (_)       / __ \
|  \| | ___  ___ ___ _  ___  / /__\/ ___ _ ____   _____ _ __
| . ` |/ _ \/ __/ __| |/ _ \ \___. \/ _ \ '__\ \ / / _ \ '__|
| |\  |  __/\__ \__ \ |  __/ /\__/ /  __/ |   \ V /  __/ |
\_| \_/\___||___/___/_|\___| \____/ \___|_|    \_/ \___|_|

                               https://projectnessie.org/

                              Powered by Quarkus 2.12.2.Final
... etc ... etc ..
```

**Comment by asheeshgarg** [comment]
I am able to download it from maven by specifying the runner type from maven. But while creating table I am getting 

Py4JJavaError: An error occurred while calling o91.sql.
: java.lang.NoSuchMethodError: 'org.projectnessie.model.GenericMetadata org.projectnessie.model.GenericMetadata.of(java.lang.String, org.apache.iceberg.shaded.com.fasterxml.jackson.databind.JsonNode)'
	at org.apache.iceberg.nessie.NessieTableOperations.doCommit(NessieTableOperations.java:174)
	at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:133)
	at org.apache.iceberg.BaseMetastoreCatalog$BaseMetastoreCatalogTableBuilder.create(BaseMetastoreCatalog.java:172)
	at org.apache.iceberg.CachingCatalog$CachingTableBuilder.lambda$create$0(CachingCatalog.java:253)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at org.apache.iceberg.CachingCatalog$CachingTableBuilder.create(CachingCatalog.java:251)
	at org.apache.iceberg.spark.SparkCatalog.createTable(SparkCatalog.java:188)
	at org.apache.iceberg.spark.SparkCatalog.createTable(SparkCatalog.java:99)
	at org.apache.spark.sql.execution.datasources.v2.CreateTableExec.run(CreateTableExec.scala:45)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)

**Comment by dimas-b** [comment]
@asheeshgarg : Please open a separate issue for the Iceberg error (it is a separate matter from the runner jar) and include info about exact Iceberg and Nessie versions and how Iceberg is configured and started.
