### ISSUE TITLE
Error while creating the iceberg Table

### ISSUE THREAD

**Issue by asheeshgarg** [projectnessie/nessie#5358]
Java 11
iceberg-spark-runtime-3.3_2.12-0.14.0.jar

Followed the notebook example
Error when creating the salary table
**What happened**:
I am able to download it from maven by specifying the runner type from maven. But while creating table I am getting

Py4JJavaError: An error occurred while calling o91.sql.
: java.lang.NoSuchMethodError: 'org.projectnessie.model.GenericMetadata org.projectnessie.model.GenericMetadata.of(java.lang.String, org.apache.iceberg.shaded.com.fasterxml.jackson.databind.JsonNode)'
at org.apache.iceberg.nessie.NessieTableOperations.doCommit(NessieTableOperations.java:174)
at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:133)
at org.apache.iceberg.BaseMetastoreCatalog$BaseMetastoreCatalogTableBuilder.create(BaseMetastoreCatalog.java:172)
at org.apache.iceberg.CachingCatalog$CachingTableBuilder.lambda$create$0(CachingCatalog.java:253)
at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406)
at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404)
at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387)
at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
at org.apache.iceberg.CachingCatalog$CachingTableBuilder.create(CachingCatalog.java:251)
at org.apache.iceberg.spark.SparkCatalog.createTable(SparkCatalog.java:188)
at org.apache.iceberg.spark.SparkCatalog.createTable(SparkCatalog.java:99)
at org.apache.spark.sql.execution.datasources.v2.CreateTableExec.run(CreateTableExec.scala:45)
at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Details**:
- Nessie server type (docker/built from source) and version:
- Client type (Ex: UI/Spark/pynessie ...) and version:

**Comment by dimas-b** [comment]
@asheeshgarg : I just tested with `spark-sql` shell and Spark 3.2 + Iceberg 0.14.0 and it worked.

Would you be able to provide your exact Spark execution command and config options (aside from secrets, of course)?

**Comment by dimas-b** [comment]
Please note that the `NessieCatalog` implementation from Iceberg must use all jars from that exact Iceberg version. Injecting new client jars is not supported.

**Comment by dimas-b** [comment]
For example, here's how to run `spark-sql`:

```
$ bin/spark-sql \
                                          --packages \
                                         org.apache.iceberg:iceberg-spark-runtime-3.2_2.12:0.14.0 \
                                          --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions  \
                                          --conf spark.sql.catalog.nessie=org.apache.iceberg.spark.SparkCatalog \
                                          --conf spark.sql.catalog.nessie.warehouse=$PWD/data2 \
                                          --conf spark.sql.catalog.nessie.catalog-impl=org.apache.iceberg.nessie.NessieCatalog \
                                          --conf spark.sql.catalog.nessie.uri=http://localhost:19120/api/v1 \
                                          --conf spark.sql.catalog.nessie.ref=main \
                                          --conf spark.sql.catalog.nessie.cache-enabled=false
```

**Comment by ajantha-bhat** [comment]
@asheeshgarg : Which Nessie version you are using with Iceberg 0.14.0? 

This is the latest compatibility matrix
https://github.com/projectnessie/nessie#compatibility

I just tried Nessie 0.43.0 with Spark 3.3 +  Iceberg 0.14.1. Things worked fine for me.

**Comment by dimas-b** [comment]
@asheeshgarg : I _suspect_ that in your env. there's some jar mismatch on the Iceberg class path.

Generally, Iceberg should be used only with its own official artifacts because it relocates some libraries.

The Nessie Server, though, can be of a newer version according to the compatibility matrix.

**Comment by asheeshgarg** [comment]
nessie-quarkus-0.43.0-runner.jar
nessie-spark-extensions-3.3_2.12-0.43.0.jar I have kept the jar in the spark/jar folder

I start the server with runner 
                               https://projectnessie.org/

                              Powered by Quarkus 2.12.2.Final
2022-10-12 13:57:59,475 WARN  [io.qua.oid.com.run.OidcCommonUtils] (vert.x-eventloop-thread-1) OIDC Server is not available:: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.255.0.0:0
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)

2022-10-12 13:57:59,506 INFO  [io.qua.sma.ope.run.OpenApiRecorder] (main) Default CORS properties will be used, please use 'quarkus.http.cors' properties instead
2022-10-12 13:57:59,906 INFO  [org.pro.qua.pro.DatabaseAdapterProvider] (main) Using INMEMORY Version store
2022-10-12 13:58:00,046 INFO  [io.quarkus] (main) nessie-quarkus 0.43.0 on JVM (powered by Quarkus 2.12.2.Final) started in 3.071s. Listening on: http://0.0.0.0:19120
2022-10-12 13:58:00,050 INFO  [io.quarkus] (main) Profile prod activated. 
2022-10-12 13:58:00,050 INFO  [io.quarkus] (main) Installed features: [agroal, amazon-dynamodb, cdi, hibernate-validator, jaeger, jdbc-postgresql, logging-sentry, micrometer, mongodb-client, narayana-jta, oidc, reactive-routes, resteasy, resteasy-jackson, security, security-properties-file, smallrye-context-propagation, smallrye-health, smallrye-openapi, smallrye-opentracing, swagger-ui, vertx]

Following parameters I used
addl_spark_conf={
"spark.sql.execution.pyarrow.enabled":"true",
"spark.sql.catalog.dev_catalog":"org.apache.iceberg.spark.SparkCatalog",
"spark.sql.catalog.dev_catalog.catalog-impl":"org.apache.iceberg.nessie.NessieCatalog",
"spark.sql.catalog.dev_catalog.warehouse":"/spark_warehouse/iceberg",
"spark.sql.catalog.dev_catalog.uri":"http://localhost:19120/api/v1",
"spark.sql.catalog.dev_catalog.ref":"main",
"spark.sql.catalog.dev_catalog.auth_type":"NONE",
"spark.sql.extensions": "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions"
}
                 
              
The branches get created fine but when I create a table above error come in the original request.

**Comment by dimas-b** [comment]
@asheeshgarg : 
> I have kept the jar in the spark/jar folder

AFAIK, nothing needs to be (manually) added to the Spark's jar directory. Spark is able to download extensions by itself (cf. the `--packages` option in my example above).

**Comment by dimas-b** [comment]
@asheeshgarg : Does this doc help? https://projectnessie.org/tools/iceberg/spark/

**Comment by asheeshgarg** [comment]
I am in the a restricted environment and jar need to be manually added to the spark container.

**Comment by dimas-b** [comment]
Interesting :thinking: Could you describe your "ideal" setup? Something like a pre-packaged Spark installation directory (tar?) that can work with Iceberg and Nessie?

**Comment by dimas-b** [comment]
What Spark shell do you use? Scala or SQL?

**Comment by asheeshgarg** [comment]
I am in Pyspark environment.

If we have a list of the jars need in Spark runtime that will help anything else apart from nessie-spark-extensions-3.3_2.12-0.43.0.jar?
Does this has any issue?
                          Powered by Quarkus 2.12.2.Final
2022-10-12 13:57:59,475 WARN [io.qua.oid.com.run.OidcCommonUtils] (vert.x-eventloop-thread-1) OIDC Server is not available:: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.255.0.0:0
Caused by: java.net.ConnectException: Connection refused
at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by dimas-b** [comment]
The `OIDC Server is not available` error is inconsequential. It basically means that OIDC is not configure. Please ignore it.

**Comment by dimas-b** [comment]
@asheeshgarg : I was able to reproduce your problem :hourglass:

**Comment by asheeshgarg** [comment]
Great hope to see a workaround.

**Comment by dimas-b** [comment]
The basic problem is #5363. It can happen even with the `packages` config option.

**Comment by dimas-b** [comment]
@asheeshgarg : how flexible is your env.? Can you afford repackaging Nessie jars?

**Comment by asheeshgarg** [comment]
I can i have java runtime. But cant build the project

**Comment by ajantha-bhat** [comment]
@asheeshgarg , 

I explicitly give jars in the config. For me, the below order works. 

`--jars /Users/ajantha/Downloads/iceberg-spark-runtime-3.3_2.12-0.14.0.jar ,/Users/ajantha/Downloads/nessie-spark-extensions-3.3_2.12-0.43.0.jar`

But when I reverse the order as below, I get the same error as you mentioned.

`--jars /Users/ajantha/Downloads/nessie-spark-extensions-3.3_2.12-0.43.0.jar,/Users/ajantha/Downloads/iceberg-spark-runtime-3.3_2.12-0.14.0.jar `

**Comment by dimas-b** [comment]
@asheeshgarg : For a workaround please try this:
1. Do not add any extra jars to the Spark's `jars` directory
2. Use the `--jars` options instead to add the pre-downloaded jars to the Spark driver and executors
3. Make sure the Iceberg jar is listed _before_ the Nessie extensions jar.

For example: `--jars /path/to/iceberg-spark-runtime-3.3_2.12-0.14.0.jar,/path/to/nessie-spark-extensions-3.3_2.12-0.43.0.jar`

Or course, use paths that are appropriate in your env.

**Comment by asheeshgarg** [comment]
That works thanks for the resolution. Let me test the full notebook
