### ISSUE TITLE
Failed to generate Jacoco reports: EOFException at `ExecutionDataReader.readExecutionData`

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#5709]
Running `./gradlew test`:
```
> Task :nessie-quarkus-cli:test
Failed to generate Jacoco reports
java.io.EOFException
        at java.base/java.io.DataInputStream.readUnsignedShort(DataInputStream.java:345)
        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:594)
        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:569)
        at org.jacoco.core.data.ExecutionDataReader.readExecutionData(ExecutionDataReader.java:149)
        at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:116)
        at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:93)
        at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:60)
        at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:74)
        at io.quarkus.jacoco.runtime.ReportCreator.run(ReportCreator.java:72)
        at java.base/java.lang.Thread.run(Thread.java:829)
Failed to generate Jacoco reports
java.io.EOFException
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272)
        at org.jacoco.core.internal.data.CompactDataInput.readBooleanArray(CompactDataInput.java:64)
        at org.jacoco.core.data.ExecutionDataReader.readExecutionData(ExecutionDataReader.java:150)
        at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:116)
        at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:93)
        at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:60)
        at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:74)
        at io.quarkus.jacoco.runtime.ReportCreator.run(ReportCreator.java:72)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by snazy** [comment]
Fixed by not letting Quarkus generate the report
