### ISSUE TITLE
Can't use minio S3 in spark-sql while using nessie

### ISSUE THREAD

**Issue by samirski** [projectnessie/nessie#5866]
**What happened**:

I'm trying to showcase nessie to my colleagues at work while using mino s3 endpoint. The frustration part is that while I'm using org.apache.iceberg.rest.RESTCatalog from tabular.io everything work, however as soon as I switch to org.apache.iceberg.nessie.NessieCatalog I start getting software.amazon.awssdk.services.s3.model.S3Exception exceptions:
    
    software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 400, Request ID: 173AB4BDC038F90C)
            at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
            at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)
            at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85)
            at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:43)
            at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:95)
            at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$7(BaseClientHandler.java:245)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
            at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
            at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
            at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
            at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
            at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
            at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
            at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
            at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
            at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
            at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:167)
            at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
            at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175)
            at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
            at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
            at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
            at software.amazon.awssdk.services.s3.DefaultS3Client.putObject(DefaultS3Client.java:9326)
            at org.apache.iceberg.aws.s3.S3OutputStream.completeUploads(S3OutputStream.java:435)
            at org.apache.iceberg.aws.s3.S3OutputStream.close(S3OutputStream.java:269)
            at java.base/sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:341)
            at java.base/sun.nio.cs.StreamEncoder.close(StreamEncoder.java:161)
            at java.base/java.io.OutputStreamWriter.close(OutputStreamWriter.java:255)
            at org.apache.iceberg.TableMetadataParser.$closeResource(TableMetadataParser.java:132)
            at org.apache.iceberg.TableMetadataParser.internalWrite(TableMetadataParser.java:132)
            at org.apache.iceberg.TableMetadataParser.overwrite(TableMetadataParser.java:115)
            at org.apache.iceberg.BaseMetastoreTableOperations.writeNewMetadata(BaseMetastoreTableOperations.java:164)
            at org.apache.iceberg.nessie.NessieTableOperations.doCommit(NessieTableOperations.java:149)
            at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:135)
            at org.apache.iceberg.BaseMetastoreCatalog$BaseMetastoreCatalogTableBuilder.create(BaseMetastoreCatalog.java:196)
            at org.apache.iceberg.spark.SparkCatalog.createTable(SparkCatalog.java:209)
            at org.apache.spark.sql.execution.datasources.v2.CreateTableExec.run(CreateTableExec.scala:45)
            at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
            at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
            at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
            at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
            at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
            at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
            at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
            at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
            at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
            at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
            at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
            at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
            at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
            at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
            at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
            at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
            at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
            at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
            at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
            at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:560)
            at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
            at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
            at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
            at org.apache.spark.sql.Dataset.<init>(Dataset.scala:220)
            at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
            at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
            at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
            at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:622)
            at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
            at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:617)
            at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:651)
            at org.apache.spark.sql.hive.thriftserver.SparkSQLDriver.run(SparkSQLDriver.scala:67)
            at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processCmd(SparkSQLCLIDriver.scala:384)
            at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.$anonfun$processLine$1(SparkSQLCLIDriver.scala:504)
            at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.$anonfun$processLine$1$adapted(SparkSQLCLIDriver.scala:498)
            at scala.collection.Iterator.foreach(Iterator.scala:943)
            at scala.collection.Iterator.foreach$(Iterator.scala:943)
            at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
            at scala.collection.IterableLike.foreach(IterableLike.scala:74)
            at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
            at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
            at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processLine(SparkSQLCLIDriver.scala:498)
            at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:286)
            at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:566)
            at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
            at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
            at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
            at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
            at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
            at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
            at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
            at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

so this works:

    spark-sql \
     --packages org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:1.1.0,software.amazon.awssdk:bundle:2.17.257,software.amazon.awssdk:url-connection-client:2.17.257 \
     --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions  \
     --conf spark.sql.catalog.nessie=org.apache.iceberg.spark.SparkCatalog \
     --conf spark.sql.catalog.nessie.warehouse=s3://warehouse/wh/ \
     --conf spark.sql.catalog.nessie.s3.endpoint=http://192.168.2.214:9000 \
     --conf spark.sql.catalog.nessie.s3.access.key=admin \
     --conf spark.sql.catalog.nessie.s3.secret.key=password \
     --conf spark.sql.catalog.nessie.io-impl=org.apache.iceberg.aws.s3.S3FileIO \
     --conf spark.sql.catalog.nessie.catalog-impl=org.apache.iceberg.rest.RESTCatalog \
     --conf spark.sql.catalog.nessie.uri=http://192.168.2.214:8181 \
     --conf spark.sql.defaultCatalog=nessie

and this does not:

    spark-sql \
     --packages org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:1.1.0,software.amazon.awssdk:bundle:2.17.257,software.amazon.awssdk:url-connection-client:2.17.257,org.projectnessie:nessie-spark-extensions-3.3_2.12:0.46.7 \
     --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions  \
     --conf spark.sql.catalog.nessie=org.apache.iceberg.spark.SparkCatalog \
     --conf spark.sql.catalog.nessie.warehouse=s3://warehouse/wh/ \
     --conf spark.sql.catalog.nessie.s3.endpoint=http://192.168.2.214:9000 \
     --conf spark.sql.catalog.nessie.s3.access.key=admin \
     --conf spark.sql.catalog.nessie.s3.secret.key=password \
     --conf spark.sql.catalog.nessie.catalog-impl=org.apache.iceberg.nessie.NessieCatalog \
     --conf spark.sql.catalog.nessie.io-impl=org.apache.iceberg.aws.s3.S3FileIO \
     --conf spark.sql.catalog.nessie.uri=http://192.168.2.214:19120/api/v1 \
     --conf spark.sql.catalog.nessie.ref=main \
     --conf spark.sql.catalog.nessie.cache-enabled=false
     --conf spark.sql.defaultCatalog=nessie

as you can see the only difference that nessie catalog is being used here, everything else is exactly the same. I've spent 2 days trying to understand what is going on here, and still don't get what I'm doing wrong.

**What you expected to happen**:

That in minio S3 would just work as in the first example.

**How to reproduce it (as minimally and precisely as possible)**:

I'm using this docker compose file as an example: https://github.com/tabular-io/docker-spark-iceberg/blob/main/docker-compose.yml to run minio server.

And using a default nessie docker image for nessie endpoint.
Also used this Docker file to download all required packages to run spark with iceberg locally.

https://github.com/tabular-io/docker-spark-iceberg/blob/main/spark/Dockerfile

**Details**:
- Nessie server type (docker/built from source) and version: docker projectnessie/nessie:0.46.7
- Client type (Ex: UI/Spark/pynessie ...) and version: https://dlcdn.apache.org/spark/spark-3.3.1/spark-3.3.1-bin-hadoop3.tgz

**Comment by ajantha-bhat** [comment]
Our documentation (https://projectnessie.org/guides/spark-s3/) suggests 
`export AWS_PROFILE=demo`

From the below Nessie Iceberg integration code it looks like `nessie.` prefix is not removed. So, AWS properties cannot be resolved if you pass them with the prefix (REST catalog might have this translation layer). 
https://github.com/apache/iceberg/blob/d57c7052586a95455645fe9800dce8b65baf1237/nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java#L101

So, as of now, I suggest using like 
a) `export AWS_PROFILE=demo` as mentioned in the docs
b) or send them as Hadoop conf like this
```
--conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
--conf spark.hadoop.fs.s3a.access.key=xxx 
--conf spark.hadoop.fs.s3a.secret.key=yyy
--conf spark.hadoop.fs.s3a.endpoint=zzz
```

c) or remove `.nessie` prefix and directly use `spark.sql.catalog.s3.access.key` instead of `spark.sql.catalog.nessie.s3.access.key` ( I haven't tried this method though)

**Comment by samirski** [comment]
@ajantha-bhat thanks for your response. Unfortunately the solutions that you have mentioned did not work. I'm still getting the same error. I can create a new branch in nessie but as soon as I'm trying to create a table it fail. I'm using an example metioned here:  https://projectnessie.org/guides/spark-s3/

**Comment by harshm-dev** [comment]
@samirski Thanks for the detailed steps. I was able to reproduce the problem locally when the warehouse path is reused. 

**If I use a different path for warehouse, the nessie demo goes through fine.**

```
 spark-sql \
 --packages org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:1.1.0,software.amazon.awssdk:bundle:2.17.257,software.amazon.awssdk:url-connection-client:2.17.257,org.projectnessie:nessie-spark-extensions-3.3_2.12:0.46.7 \
 --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions  \
 --conf spark.sql.catalog.nessie=org.apache.iceberg.spark.SparkCatalog \
 --conf spark.sql.catalog.nessie.warehouse=s3://warehouse/nessie-wh \
 --conf spark.sql.catalog.nessie.s3.endpoint=http://localhost:9000 \
 --conf spark.sql.catalog.nessie.s3.access.key=admin \
 --conf spark.sql.catalog.nessie.s3.secret.key=password \
 --conf spark.sql.catalog.nessie.catalog-impl=org.apache.iceberg.nessie.NessieCatalog \
 --conf spark.sql.catalog.nessie.io-impl=org.apache.iceberg.aws.s3.S3FileIO \
 --conf spark.sql.catalog.nessie.uri=http://localhost:19120/api/v1 \
 --conf spark.sql.catalog.nessie.ref=main \
 --conf spark.sql.catalog.nessie.cache-enabled=false
 --conf spark.sql.defaultCatalog=nessie
```

```
spark-sql> create table nessie_db.demo (C1 int) using iceberg;
Time taken: 1.66 seconds
spark-sql> insert into nessie_db.demo values (1);
Time taken: 5.563 seconds
```

Though I didn't spend enough time, there's a high chance that object locking is enabled on the "warehouse" path and it's somehow conflicting at the PUT. The minio implementation is potentially misleading - as it responds with 400 null at server, with not much info in the logs. However, the trace console confirms that server responded as mentioned.

Please try with one or more of following combinations - 

- Different warehouse path within same bucket (as mentioned in the command above)
- Create a different bucket in minio without object locking, and use the same
- Restart minio, so the locks are released. Then try the nessie side operations

**Comment by samirski** [comment]
@harshm-dev a HUGE thank you for looking into that! I can confirm it's also working on my end. Closing this one.
