### ISSUE TITLE
Nessie helm chart: Fatal error: Failed while initializing the performance data.

### ISSUE THREAD

**Issue by julwin** [projectnessie/nessie#5900]
Hi everyone, when running the helm chart (with default configuration except for security context below), I immediately get the following error message, the container is not starting up.

```yaml
securityContext: 
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001
```

```
Fatal error: Failed while initializing the performance data.

Current timestamp: 1674126078974

Printing Instructions (ip=0x0000000000dc7240):
  0x0000000000dc7220: 0x00 0x41 0xc7 0x87 0x4c 0x01 0x00 0x00 0xfe 0xfe 0xfe 0x7e 0x48 0x8b 0x7c 0x24
  0x0000000000dc7230: 0x20 0x48 0x8b 0x74 0x24 0x10 0x48 0x8b 0x54 0x24 0x18 0xe8 0x60 0xfd 0xff 0xff
  0x0000000000dc7240: 0x90 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc
  0x0000000000dc7250: 0x48 0x83 0xec 0x18 0x49 0x3b 0x67 0x08 0x0f 0x86 0x9f 0x00 0x00 0x00 0x48 0x8b

Top of stack (sp=0x00007a5d132fedc0):
  0x00007a5d132fedc0: 0x0000800000008000 0x0000000000e31563
  0x00007a5d132fedd0: 0x00007a5d1594ebf8 0x00007a5d13f00000
  0x00007a5d132fede0: 0x0000000000e13eeb 0x0000000000ecf234
  0x00007a5d132fedf0: 0x00007a5d16eeb100 0x0000000000e13eeb
  0x00007a5d132fee00: 0x0000000000e3611b 0x00007a5d17339a28
  0x00007a5d132fee10: 0x00007a5d169a2048 0x0000000000e13f3b
  0x00007a5d132fee20: 0x00007a5d132ff700 0x0000000000e359b9
  0x00007a5d132fee30: 0x00007a5d168c4868 0x00007a5d17686860
  0x00007a5d132fee40: 0x00007a5d169a2048 0x0000000000ec678a
  0x00007a5d132fee50: 0x00007ffe77c2febf 0x00007a5d13f00000
  0x00007a5d132fee60: 0x00007a5d169a2048 0x00007a5d16f97a48
  0x00007a5d132fee70: 0x0000000000000002 0x0000000000e35fc7
  0x00007a5d132fee80: 0x00007a5d13f00000 0x0000000100000000
  0x00007a5d132fee90: 0x0000000000000002 0x0000000000d7219f
  0x00007a5d132feea0: 0x0000000000000000 0x0000000000000000
  0x00007a5d132feeb0: 0x0000000000000000 0x0000000000000000
  0x00007a5d132feec0: 0x0000000009ca4cc0 0x0000000000000000
  0x00007a5d132feed0: 0x00007a5d132fefc0 0x00007ffe77c2ff80
  0x00007a5d132feee0: 0x00007ffe77c2febf 0x00007ffe77c2febe
  0x00007a5d132feef0: 0x0000000000000000 0x00007a5d1a4a91ca
  0x00007a5d132fef00: 0x0000000000000000 0x00007a5d132ff700
  0x00007a5d132fef10: 0x00007a5d132ff700 0xa0ee031636f2f41e
  0x00007a5d132fef20: 0x00007ffe77c2febe 0x00007ffe77c2febf
  0x00007a5d132fef30: 0x00007ffe77c2ff80 0x00007a5d132fefc0
  0x00007a5d132fef40: 0x54542549e8f2f41e 0x545437831420f41e
  0x00007a5d132fef50: 0x0000000000000000 0x0000000000000000
  0x00007a5d132fef60: 0x0000000000000000 0x0000000000000000
  0x00007a5d132fef70: 0x0000000000000000 0x0000000000000000
  0x00007a5d132fef80: 0x0000000000000000 0x0000000000000000
  0x00007a5d132fef90: 0x0000000000000000 0x09933a09094df400
  0x00007a5d132fefa0: 0x0000000000000000 0x00007a5d132ff700
  0x00007a5d132fefb0: 0x00007ffe77c2ff80 0x00007a5d19d08e73

Top frame info:
  TotalFrameSize in CodeInfoTable 48
  
Threads:
  0x00007a5d04000b80 STATUS_IN_JAVA (PREVENT_VM_FROM_REACHING_SAFEPOINT) "Performance data" - 0x00007a5d169a2048, daemon, stack(0x00007a5d12b01000,0x00007a5d13300000)
  0x00007a5d0c000b80 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "Reference Handler" - 0x00007a5d169a3d38, daemon, stack(0x00007a5d13501000,0x00007a5d13d00000)
  0x0000000009ca4340 STATUS_IN_JAVA (ALLOW_SAFEPOINT) "main" - 0x00007a5d169a3c78, stack(0x00007ffe77432000,0x00007ffe77c31000)
  
VM thread locals for the failing thread 0x00007a5d04000b80:
  0 (8 bytes): JNIThreadLocalEnvironment.jniFunctions = (bytes) 
    0x00007a5d04000b80: 0x00007a5d15ee4010
  8 (8 bytes): StackOverflowCheckImpl.stackBoundaryTL = (Word) 1 (0x0000000000000001)
  16 (4 bytes): Safepoint.safepointRequested = (int) 2147470175 (0x7fffcb5f)
  20 (4 bytes): StatusSupport.statusTL = (int) 1 (0x00000001)
  24 (32 bytes): ThreadLocalAllocation.regularTLAB = (bytes) 
    0x00007a5d04000b98: 0x00007a5d12900000 0x00007a5d12a00000
    0x00007a5d04000ba8: 0x00007a5d129014f0 0x0000000000000000
  56 (8 bytes): PlatformThreads.currentThread = (Object) com.oracle.svm.core.jvmstat.PerfManager$PerfDataThread (0x00007a5d169a2048)
  64 (8 bytes): JavaFrameAnchors.lastAnchor = (Word) 0 (0x0000000000000000)
  72 (8 bytes): AccessControlContextStack = (Object) null
  80 (8 bytes): ExceptionUnwind.currentException = (Object) null
  88 (8 bytes): IdentityHashCodeSupport.hashCodeGeneratorTL = (Object) null
  96 (8 bytes): IsolatedCompileClient.currentClient = (Object) null
  104 (8 bytes): IsolatedCompileContext.currentContext = (Object) null
  112 (8 bytes): JNIObjectHandles.handles = (Object) com.oracle.svm.core.handles.ThreadLocalHandles (0x00007a5d12901208)
  120 (8 bytes): JNIThreadLocalPendingException.pendingException = (Object) null
  128 (8 bytes): JNIThreadLocalPinnedObjects.pinnedObjectsListHead = (Object) null
  136 (8 bytes): JNIThreadOwnedMonitors.ownedMonitors = (Object) null
  144 (8 bytes): JfrThreadLocal.javaEventWriter = (Object) null
  152 (8 bytes): NoAllocationVerifier.openVerifiers = (Object) null
  160 (8 bytes): ThreadingSupportImpl.activeTimer = (Object) null
  168 (8 bytes): JfrThreadLocal.dataLost = (Word) 0 (0x0000000000000000)
  176 (8 bytes): JfrThreadLocal.javaBuffer = (Word) 0 (0x0000000000000000)
  184 (8 bytes): JfrThreadLocal.nativeBuffer = (Word) 0 (0x0000000000000000)
  192 (8 bytes): JfrThreadLocal.parentThreadId = (long) 1 (0x0000000000000001)
  200 (8 bytes): JfrThreadLocal.threadId = (long) 17 (0x0000000000000011)
  208 (8 bytes): SamplerThreadLocal.localBuffer = (Word) 0 (0x0000000000000000)
  216 (8 bytes): SamplerThreadLocal.missedSamples = (long) 0 (0x0000000000000000)
  224 (8 bytes): SamplerThreadLocal.unparseableStacks = (long) 0 (0x0000000000000000)
  232 (8 bytes): SamplerThreadLocal.writerData = (Word) 0 (0x0000000000000000)
  240 (8 bytes): SubstrateDiagnostics.threadOnlyAttachedForCrashHandler = (bytes) 
    0x00007a5d04000c70: 0x0000000000000000
  248 (8 bytes): ThreadLocalAllocation.allocatedBytes = (Word) 0 (0x0000000000000000)
  256 (8 bytes): VMThreads.IsolateTL = (Word) 134540185042944 (0x00007a5d13f00000)
  264 (8 bytes): VMThreads.OSThreadHandleTL = (Word) 134540172457728 (0x00007a5d132ff700)
  272 (8 bytes): VMThreads.OSThreadIdTL = (Word) 134540172457728 (0x00007a5d132ff700)
  280 (8 bytes): VMThreads.StackBase = (Word) 134540172460032 (0x00007a5d13300000)
  288 (8 bytes): VMThreads.StackEnd = (Word) 134540164075520 (0x00007a5d12b01000)
  296 (8 bytes): VMThreads.StartedByCurrentIsolate = (bytes) 
    0x00007a5d04000ca8: 0x0000000000000001
  304 (8 bytes): VMThreads.nextTL = (Word) 134540051876736 (0x00007a5d0c000b80)
  312 (8 bytes): VMThreads.unalignedIsolateThreadMemoryTL = (Word) 134539917658976 (0x00007a5d04000b60)
  320 (4 bytes): ActionOnExitSafepointSupport.actionTL = (int) 0 (0x00000000)
  324 (4 bytes): ActionOnTransitionToJavaSupport.actionTL = (int) 0 (0x00000000)
  328 (4 bytes): ImplicitExceptions.implicitExceptionsAreFatal = (int) 0 (0x00000000)
  332 (4 bytes): StackOverflowCheckImpl.yellowZoneStateTL = (int) 2130640638 (0x7efefefe)
  336 (4 bytes): StatusSupport.safepointBehaviorTL = (int) 1 (0x00000001)
  340 (4 bytes): ThreadingSupportImpl.currentPauseDepth = (int) 0 (0x00000000)
  
No VMOperation in progress

The 15 most recent VM operation status changes (oldest first):
  
Counters:
  
Java frame anchors for the failing thread 0x00007a5d04000b80:
  No anchors
  
Stacktrace for the failing thread 0x00007a5d04000b80:
  SP 0x00007a5d132fedc0 IP 0x0000000000dc7240  [image code] com.oracle.svm.core.jdk.VMErrorSubstitutions.shutdown(VMErrorSubstitutions.java:116)
  SP 0x00007a5d132fedc0 IP 0x0000000000dc7240  [image code] com.oracle.svm.core.jdk.VMErrorSubstitutions.shouldNotReachHere(VMErrorSubstitutions.java:109)
  SP 0x00007a5d132fedf0 IP 0x0000000000ecf234  [image code] com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:65)
  SP 0x00007a5d132fee00 IP 0x0000000000e13eeb  [image code] com.oracle.svm.core.util.VMError.guarantee(VMError.java:89)
  SP 0x00007a5d132fee00 IP 0x0000000000e13eeb  [image code] com.oracle.svm.core.jvmstat.PerfManager$PerfDataThread.initializeMemory(PerfManager.java:208)
  SP 0x00007a5d132fee20 IP 0x0000000000e13f3b  [image code] com.oracle.svm.core.jvmstat.PerfManager$PerfDataThread.run(PerfManager.java:187)
  SP 0x00007a5d132fee50 IP 0x0000000000ec678a  [image code] com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
  SP 0x00007a5d132fee80 IP 0x0000000000e35fc7  [image code] com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
  SP 0x00007a5d132feea0 IP 0x0000000000d7219f  [image code] com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_cf47bd191b082a3631657d369b9255c828b9a95c(IsolateEnterStub.java:0)
  
VM mutexes:
  mutex "jfrThreadRepository" is unlocked.
  mutex "mainVMOperationControlWorkQueue" is unlocked.
  mutex "perfDataInitialization" is locked by thread 0x00007a5d04000b80
  mutex "referencePendingList" is unlocked.
  mutex "thread" is unlocked.
  mutex "jfrSymbolRepository" is unlocked.
  mutex "SamplerBufferPool" is unlocked.
  mutex "jfrRecorder" is unlocked.
  
AOT compiled code is mapped at 0x0000000000407000 - 0x000000000355147f

Heap settings and statistics:
  Supports isolates: true
  Heap base: 0x00007a5d13f00000
  Object reference size: 8
  Aligned chunk size: 1048576
  Incremental collections: 0
  Complete collections: 0
  
Native image heap boundaries:
  ReadOnly Primitives: 0x00007a5d14001028 - 0x00007a5d1579de70
  ReadOnly References: 0x00007a5d1579de70 - 0x00007a5d15ee3208
  ReadOnly Relocatables: 0x00007a5d15ee4000 - 0x00007a5d1658ef30
  Writable Primitives: 0x00007a5d1658f000 - 0x00007a5d167cf5a8
  Writable References: 0x00007a5d167cf5a8 - 0x00007a5d17846ed8
  Writable Huge: 0x00007a5d17900030 - 0x00007a5d17c7d0f8
  ReadOnly Huge: 0x00007a5d17c7e030 - 0x00007a5d19cbcff8

Heap:
  Young generation: 
    Eden: 
      edenSpace:
        aligned: 0/0 unaligned: 0/0
    Survivors: 
      Survivor-1 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-1 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-2 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-2 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-3 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-3 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-4 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-4 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-5 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-5 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-6 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-6 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-7 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-7 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-8 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-8 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-9 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-9 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-10 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-10 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-11 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-11 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-12 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-12 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-13 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-13 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-14 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-14 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-15 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-15 To:
        aligned: 0/0 unaligned: 0/0
  Old generation: 
    oldFromSpace:
      aligned: 0/0 unaligned: 0/0
    oldToSpace:
      aligned: 0/0 unaligned: 0/0
    
  Unused:
    aligned: 0/0

Fatal error: Failed while initializing the performance data.

```

**Comment by snazy** [comment]
@julwin thanks for the report. Do you have any more detailed steps how to reproduce this one, because CI does not fail.

**Comment by julwin** [comment]
Thanks for your quick response, @snazy! I'll try to give you some more detail:

- Running the helm chart against a private k8s cluster (without access to the internet, if that matters)
- Pulling the image (0.47.0 and 0.46.0 tested) from docker hub
- Cluster has a policy to let contains run only with a non-root user, so I commented out the section with securityContext from the helm chart

Anything else you are interested in?

**Comment by snazy** [comment]
Doesn't look like a Nessie issue though. There's a [matching issue in Graal](https://github.com/oracle/graal/issues/5303), which [let Quarkus use the Mandrel build images](https://github.com/quarkusio/quarkus/issues/29252), which we also use.

I've created a PR to disable (JVM) monitoring for native images for now. Can you try and see if that change fixes the problem? Git branch is here: https://github.com/snazy/nessie/tree/quarkus-no-monitoring . You can build the Docker image via `./gradlew  :nessie-quarkus:quarkusBuild -Pnative -Pdocker`.

**Comment by snazy** [comment]
> unfortunately I have no gradle setup configured

Don't need anything else than Java 11 SDK - `gradlew` is a script that pulls everything that's needed

**Comment by julwin** [comment]
Hm I' getting an error with the build:

```
Status: Downloaded newer image for quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
Warning: Using a deprecated option --allow-incomplete-classpath from 'META-INF/native-image/software.amazon.awssdk/netty-nio-client/native-image.properties' in 'file:///project/lib/software.amazon.awssdk.netty-nio-client-2.18.41.jar'. Allowing an incomplete classpath is now the default. Use --link-at-build-time to report linking errors at image build time for a class or package.
Fatal error: com.oracle.svm.core.util.VMError$HostedError: java.nio.file.FileSystemException: /project: Operation not permitted
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoaderSupport$ClassInit.loadClassesFromPath(NativeImageClassLoaderSupport.java:706)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoaderSupport$ClassInit.loadClassesFromPath(NativeImageClassLoaderSupport.java:662)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.nio.file.FileSystemException: /project: Operation not permitted
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.asIOException(UnixException.java:115)
        at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:168)
        at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.hasNext(UnixDirectoryStream.java:198)
        at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:349)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2845)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoaderSupport$ClassInit.loadClassesFromPath(NativeImageClassLoaderSupport.java:704)
        ... 11 more
Error: Image build request failed with exit status 1

> Task :nessie-quarkus:quarkusBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nessie-quarkus:quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 1
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:421)
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:262)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:1589)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8m 27s
```

**Comment by snazy** [comment]
Weird error. Sorry, no clue what may cause that.
We've merged the change, so it'll be in the next release.

**Comment by snazy** [comment]
Nessie 0.47.1 has been released. @julwin can you give that a try?

**Comment by julwin** [comment]
Sure, I'll test it.

**Comment by julwin** [comment]
I can confirm that this solves the issue I was having 😄 . Thanks again for solving this so quickly! 👍
