### ISSUE TITLE
HTTP 404 client errors are hard to read/debug

### ISSUE THREAD

**Issue by XN137** [projectnessie/nessie#7953]
### Issue description

example:
```
org.projectnessie.client.rest.NessieServiceException: 
Not Found (HTTP/404): 

Additionally, the client-side exception below was caught while decoding the HTTP response:
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `org.projectnessie.error.ImmutableNessieError` from [Unavailable value] (token `JsonToken.NOT_AVAILABLE`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1752)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1526)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1473)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:224)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2079)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1229)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1247)
	at com.fasterxml.jackson.databind.ObjectReader.treeToValue(ObjectReader.java:2024)
	at org.projectnessie.client.rest.ResponseCheckFilter.decodeErrorObject(ResponseCheckFilter.java:111)
	at org.projectnessie.client.rest.ResponseCheckFilter.checkResponse(ResponseCheckFilter.java:55)
	at org.projectnessie.client.rest.NessieHttpResponseFilter.filter(NessieHttpResponseFilter.java:29)
	at org.projectnessie.client.http.impl.jdk11.JavaRequest.lambda$executeRequest$1(JavaRequest.java:140)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at org.projectnessie.client.http.impl.jdk11.JavaRequest.executeRequest(JavaRequest.java:140)
	at org.projectnessie.client.http.HttpRequest.get(HttpRequest.java:88)
	at org.projectnessie.client.rest.v1.RestV1TreeClient.getReferenceByName(RestV1TreeClient.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.projectnessie.client.rest.v1.RestV1Client$ExceptionRewriter.invoke(RestV1Client.java:84)
	at com.sun.proxy.$Proxy188.getReferenceByName(Unknown Source)
	at org.projectnessie.client.rest.v1.HttpGetReference.get(HttpGetReference.java:34)
	at org.apache.iceberg.nessie.NessieViewCatalog.loadReference(NessieViewCatalog.java:133)
	at org.apache.iceberg.nessie.NessieViewCatalog.initialize(NessieViewCatalog.java:100)
	at org.apache.iceberg.nessie.NessieExtCatalog.initialize(NessieExtCatalog.java:48)
(...)
	Suppressed: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `org.projectnessie.error.ImmutableNessieError` from [Unavailable value] (token `JsonToken.NOT_AVAILABLE`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
		at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
		at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1752)
		at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1526)
		at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1473)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:224)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
		at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
		at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2079)
		at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1229)
		at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1247)
		at com.fasterxml.jackson.databind.ObjectReader.treeToValue(ObjectReader.java:2024)
		at org.projectnessie.client.rest.ResponseCheckFilter.decodeErrorObject(ResponseCheckFilter.java:111)
		at org.projectnessie.client.rest.ResponseCheckFilter.checkResponse(ResponseCheckFilter.java:55)
		... 20 more
```

this shows a few problems imo:

a) the complex-looking jackson error/stacktrace basically means that the server reply was empty (which shouldnt be that uncommon for 404s)

b) the suppression at the end repeats/duplicates the previous information (i.e. same jackson parsing error)

c) there is no information what URL the http request had been sent to (i.e. maybe there was a trivial misconfiguration around the api version endpoint. maybe a similar problem exists for connection refused/Unauthorized errors? i.e. hard to debug)

d) from the stacktrace we see `RestV1TreeClient.getReferenceByName` getting called, however `org.projectnessie.error.NessieReferenceNotFoundException` is not thrown...should it?
the exception type name `NessieServiceException` might suggest to the user that there was a problem in the nessie service... however if the user misconfigured the client endpoint or the reference name does not exist, both are mistakes on the user's end (can a user differentiate between the 2 from the error message?)

**Comment by snazy** [comment]
Fixed by #8226
