### ISSUE TITLE
DBT with Nessie: ParseException

### ISSUE THREAD

**Issue by matepek** [projectnessie/nessie#8221]
### Issue description

Hello,

Running DBT with Nessie as follows results in:
```
    == SQL ==
    /* {"app": "dbt", "dbt_version": "1.7.9", "profile_name": "spark", "target_name": "prod", "node_id": "model.spark.sandbox__iceberg_table"} */

            CREATE BRANCH IF NOT EXISTS test IN iceberg_catalog
    ---------------^^^

    	at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(parsers.scala:257)
    	at org.apache.spark.sql.catalyst.parser.AbstractParser.parse(parsers.scala:98)
    	at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:54)
    	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(AbstractSqlParser.scala:68)
    	at org.apache.spark.sql.catalyst.parser.extensions.NessieSparkSqlExtensionsParser.parsePlan(NessieSparkSqlExtensionsParser.scala:114)
    	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSparkSqlExtensionsParser.parsePlan(IcebergSparkSqlExtensionsParser.scala:126)
    	at org.apache.spark.sql.SparkSession.$anonfun$sql$5(SparkSession.scala:684)
    	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:138)
    	at org.apache.spark.sql.SparkSession.$anonfun$sql$4(SparkSession.scala:683)
    	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
    	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:682)
    	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:713)
    	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:744)
    	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:651)
    	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:227)
    	... 16 more
```

Found this and indeed solved it for me: [link](
https://stackoverflow.com/questions/76581576/syntax-error-when-using-nessie-commands-with-dbt-but-not-using-spark)

Setup:
- Spark 3.5.1
- Nessie 0.79.0
- Iceberg 1.5.1
- DBT 1.7.9
- `dbt_project.yml`:
   ```
  pre-hook:
    - 'CREATE BRANCH IF NOT EXISTS test IN iceberg_catalog;'
    - 'USE REFERENCE test IN iceberg_catalog;'
   ```

Reproduce:
Execute:
```sql
/* {"app": "dbt", "dbt_version": "1.7.9", "profile_name": "spark", "target_name": "prod", "node_id": "model.spark.sandbox__iceberg_table"} */

CREATE BRANCH IF NOT EXISTS test IN iceberg_catalog
```

I'm not even sure it's a bug yet (would need to dig deeper) but wanted to share in case someone bumps into it.

Bests,

**Comment by dimas-b** [comment]
Indeed, leading comments seem to affect Nessie-specific SQL parsing.
```
spark-sql ()> USE REFERENCE main;
Branch	main	2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d
Time taken: 0.69 seconds, Fetched 1 row(s)
spark-sql ()> /* test */ USE REFERENCE main;

[PARSE_SYNTAX_ERROR] Syntax error at or near 'main': extra input 'main'.(line 1, pos 25)

== SQL ==
/* test */ USE REFERENCE main
-------------------------^^^
```

**Comment by matepek** [comment]
(Also I would like to just mention that drop schema cascade doesn't work. Complains that the schema is not empty.)

**Comment by dimas-b** [comment]
If the schema (Nessie namespace, I assume) is indeed not empty that would be expected behaviour. Nessie does not silently cascade deletes.

**Comment by matepek** [comment]
Even when I explicitly add `CASCADE` keyword?

**Comment by matepek** [comment]
BTW great project!! When I will have time I will see how I can contribute. 

I'm just sad some issues blocks me currently not to add to the system. (Actually that issue is none of the aboves. I cannot tell DBT to use a specific branch. I have tried `sql_headers`, `pre-hook`, configs. nothing worked. I mean they worked but partially. I could override the all the related macros but it just not worth the effort. That would make us stuck at a version. It's not relevant to this issue just mentioning.)
