### ISSUE TITLE
`nessie-quarkus` uber-jar broken since #8383

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#8390]
This works:
```bash
./gradlew :nessie-quarkus:quarkusBuild
java -jar servers/quarkus-server/build/quarkus-app/quarkus-run.jar 
```

This does NOT work:
```bash
./gradlew :nessie-quarkus:quarkusBuild -Puber-jar
java -jar servers/quarkus-server/build/nessie-quarkus-0.80.1-SNAPSHOT-runner.jar
```

Results in:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 12 more
Caused by: java.lang.NoSuchMethodError: 'void org.projectnessie.api.v2.params.AbstractParams.__quarkus_init_converter__maxRecords(org.jboss.resteasy.reactive.server.core.Deployment)'
	at io.quarkus.rest.runtime.__QuarkusInit.init(Unknown Source)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder.createDeployment(ResteasyReactiveRecorder.java:155)
	at io.quarkus.deployment.steps.ResteasyReactiveProcessor$setupDeployment713137389.deploy_6(Unknown Source)
	at io.quarkus.deployment.steps.ResteasyReactiveProcessor$setupDeployment713137389.deploy(Unknown Source)
	... 13 more
```

Probably "caused" by #8383

**Comment by snazy** [comment]
Pinged [on Quarkus-dev](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Resteasy.20reactive.20.2B.20uber-jar.20build.20broken/near/435031738)
