### ISSUE TITLE
[Bug]: Nessie-GC: During expire phase on Azure ADSL, the StorageUri's of the files to delete contain a duplicate portion of the relative path to the object. 

### ISSUE THREAD

**Issue by kbobrien** [projectnessie/nessie#8659]
### What happened

We are rolling out Nessie GC tool (0.83.2) on an Azure ADSL Iceberg deployment and while the tool is running successfully and cleaning up some files, we are also getting a large number of 404's for some files while the tool is trying to delete them. The URI of the file it is trying to delete contains a duplicate portion of the relative path to the object.

Real storage path:

```
abfs://storage-container@storage-account.dfs.core.windows.net/iceberg/warehouse/t1_4b441898-d38a-4136-8cb8-612ffe2709e9/metadata/00000-2096d1d9-68a4-4a8f-90fc-a8e794c8cfaf.metadata.json
```

Path GC is trying to delete, notice the duplicated path prefix:
```
abfs://storage-container@storage-account.dfs.core.windows.net/iceberg/warehouse/t1_4b441898-d38a-4136-8cb8-612ffe2709e9/iceberg/warehouse/t1_4b441898-d38a-4136-8cb8-612ffe2709e9/metadata/00000-2096d1d9-68a4-4a8f-90fc-a8e794c8cfaf.metadata.json
```

The metadata_location in the gc_live_set_contents table is:
```
abfs://storage-container@storage-account.dfs.core.windows.net/iceberg/warehouse/t1_4b441898-d38a-4136-8cb8-612ffe2709e9/metadata/00000-2096d1d9-68a4-4a8f-90fc-a8e794c8cfaf.metadata.json
```

The base_location in the gc_live_set_content_locations table is:
```
abfs://storage-container@storage-account.dfs.core.windows.net/iceberg/warehouse/t1_4b441898-d38a-4136-8cb8-612ffe2709e9/
```

Full stacktrace is:

```
2024-05-28 12:08:19,314 [iceberg-worker-pool-0] WARN  o.a.iceberg.azure.adlsv2.ADLSFileIO - Failed to delete path: abfs://storage-container@storage-account.dfs.core.windows.net/iceberg/warehouse/t1_4b441898-d38a-4136-8cb8-612ffe2709e9/iceberg/warehouse/t1_4b441898-d38a-4136-8cb8-612ffe2709e9/metadata/00000-2096d1d9-68a4-4a8f-90fc-a8e794c8cfaf.metadata.json
com.azure.storage.file.datalake.models.DataLakeStorageException: Status code 404, "{"error":{"code":"PathNotFound","message":"The specified path does not exist.\nRequestId:6da857e0-b01f-0015-28f7-b02c51000000\nTime:2024-05-28T12:08:19.3133820Z"}}"
    at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
    at com.azure.core.implementation.MethodHandleReflectiveInvoker.invokeWithArguments(MethodHandleReflectiveInvoker.java:39)
    at com.azure.core.implementation.http.rest.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:53)
    at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:408)
    at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:137)
       ....
    Suppressed: java.lang.Exception: #block terminated with an error
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:100)
        at reactor.core.publisher.Mono.block(Mono.java:1742)
        at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:147)
        at com.azure.storage.file.datalake.DataLakeFileClient.deleteWithResponse(DataLakeFileClient.java:200)
        at com.azure.storage.file.datalake.DataLakeFileClient.delete(DataLakeFileClient.java:166)
        at org.apache.iceberg.azure.adlsv2.ADLSFileIO.deleteFile(ADLSFileIO.java:92)
        at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413)
        at org.apache.iceberg.util.Tasks$Builder.access$300(Tasks.java:69)
        at org.apache.iceberg.util.Tasks$Builder$1.run(Tasks.java:315)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        ... 1 common frames omitted
```

### How to reproduce it

1. Create an Azure storage account with a nessie catalog and write some Iceberg data to it via Spark or Trino. 
2. Run `Nessie-GC:0.83.2` against that nessie catalog/storage:
```
java -jar nessie-gc.jar gc \
  --uri http://localhost:19120/api/v2 \
  --jdbc \
  --jdbc-url jdbc:postgresql://localhost:5432/nessie_gc \
  --jdbc-user pguser \
  --jdbc-password mysecretpassword
```

I've been trying to troubleshoot in the code but I cannot figure out where the path is getting duplicated. I have a feeling it might be somewhere in the org.projectnessie.gc.iceberg.IcebergContentToFiles#extractFiles method. Any suggestions or pointers would be greatly appreciated.

### Nessie server type (docker/uber-jar/built from source) and version

Kubernetes docker 0.83.2

### Client type (Ex: UI/Spark/pynessie ...) and version

Nessie GC via Kubernetes Job
Version 0.83.2

### Additional information

Discussed this issue initially on Zulip chat: https://project-nessie.zulipchat.com/#narrow/stream/371192-users/topic/Nessie.20GC.20tool.20on.20ADSL.20getting.20404's.20for.20blob.20objects

Possibly related to [#8420](https://github.com/projectnessie/nessie/issues/8420) - potentially something in `org.projectnessie.gc.files.FileReference#absolutePath or the .relativize()` stuff at the end of `org.projectnessie.gc.iceberg.IcebergContentToFiles#extractFiles`

**Comment by kbobrien** [comment]
I built a docker container locally using PR [#8661](https://github.com/projectnessie/nessie/pull/8661) and deployed it in our K8S lab to test against real data on Azure ADLSv2. Everything worked as expected and the files are now getting deleted.

```
Finished Nessie-GC identify phase finished with status IDENTIFY_SUCCESS after PT3.404244S, live-content-set ID is 5f2cf659-2941-44e0-9642-9461b786d40c.
2024-05-30 13:26:40,025 [main] INFO  o.p.g.e.local.DefaultLocalExpire - live-set#5f2cf659-2941-44e0-9642-9461b786d40c: Starting expiry.
2024-05-30 13:26:40,216 [ForkJoinPool-3-worker-4] INFO  org.apache.iceberg.CatalogUtil - Loading custom FileIO implementation: org.apache.iceberg.azure.adlsv2.ADLSFileIO
2024-05-30 13:26:40,522 [ForkJoinPool-3-worker-4] WARN  c.a.c.h.netty.implementation.Utility - The following Netty dependencies have versions that do not match the versions specified in the azure-core-http-netty pom.xml file. This may result in unexpected behavior. If your application runs without issue this message can be ignored, otherwise please update the Netty dependencies to match the versions specified in the pom.xml file. Versions found in runtime: 'io.netty:netty-common' version not found (expected: 4.1.101.Final),'io.netty:netty-handler' version not found (expected: 4.1.101.Final),'io.netty:netty-handler-proxy' version not found (expected: 4.1.101.Final),'io.netty:netty-buffer' version not found (expected: 4.1.101.Final),'io.netty:netty-codec' version not found (expected: 4.1.101.Final),'io.netty:netty-codec-http' version not found (expected: 4.1.101.Final),'io.netty:netty-codec-http2' version not found (expected: 4.1.101.Final),'io.netty:netty-transport-native-epoll' version: 4.1.100.Final (expected: 4.1.101.Final)
2024-05-30 13:26:53,614 [ForkJoinPool-3-worker-2] INFO  o.p.g.expire.PerContentDeleteExpired - live-set#5f2cf659-2941-44e0-9642-9461b786d40c content#46b37299-d0e2-4d35-a022-c98a8bdbce50: Found 5 total files in base location abfs://<REDACTED>@<REDACTED>.dfs.core.windows.net/iceberg/warehouse/t1_4b441898-d38a-4136-8cb8-612ffe2709e9/, 0 files considered expired, 5 files considered live, 0 files are newer than max-file-modification-time.
2024-05-30 13:26:53,708 [ForkJoinPool-3-worker-4] INFO  o.p.g.expire.PerContentDeleteExpired - live-set#5f2cf659-2941-44e0-9642-9461b786d40c content#f0746e53-4bc7-4419-8433-a0fcef1f6e46: Found 5 total files in base location abfs://<REDACTED>@<REDACTED>.dfs.core.windows.net/iceberg/warehouse/t1_555eb54d-8179-4252-a928-5b1ab20ced76/, 0 files considered expired, 5 files considered live, 0 files are newer than max-file-modification-time.
2024-05-30 13:26:53,708 [ForkJoinPool-3-worker-1] INFO  o.p.g.expire.PerContentDeleteExpired - live-set#5f2cf659-2941-44e0-9642-9461b786d40c content#e3b82ab0-18e5-4e7b-9fdd-fb96c3b3ab25: Found 5 total files in base location abfs://<REDACTED>@<REDACTED>.dfs.core.windows.net/warehouse/warehouse/t1_e1db2200-f9c1-48d5-bf38-ecf94781b351/, 0 files considered expired, 5 files considered live, 0 files are newer than max-file-modification-time.
2024-05-30 13:26:53,711 [ForkJoinPool-3-worker-3] INFO  o.p.g.expire.PerContentDeleteExpired - live-set#5f2cf659-2941-44e0-9642-9461b786d40c content#f74cad7b-8237-468b-8d7e-8dc284deb49f: Found 6 total files in base location abfs://<REDACTED>@<REDACTED>.dfs.core.windows.net/iceberg/warehouse/raw_101_298c61ed-902d-4f4c-8347-dca3840cb0c9/, 0 files considered expired, 6 files considered live, 0 files are newer than max-file-modification-time.
2024-05-30 13:26:55,011 [ForkJoinPool-3-worker-2] INFO  o.p.g.expire.PerContentDeleteExpired - live-set#5f2cf659-2941-44e0-9642-9461b786d40c content#76cb03c9-f10a-4d91-984d-b5d19a804afd: Found 5 total files in base location abfs://<REDACTED>@<REDACTED>.dfs.core.windows.net/warehouse/t1_2e8133c8-5c5a-4f0f-8f79-754939bb10ab/, 0 files considered expired, 5 files considered live, 0 files are newer than max-file-modification-time.
2024-05-30 13:26:55,212 [ForkJoinPool-3-worker-4] INFO  o.p.g.expire.PerContentDeleteExpired - live-set#5f2cf659-2941-44e0-9642-9461b786d40c content#3242292d-dcb0-4e4b-9f69-ef04b23f19c5: Found 5 total files in base location abfs://<REDACTED>@<REDACTED>.dfs.core.windows.net/iceberg/warehouse/t1_90b3bef1-c067-4d7d-b78d-6363441a176e/, 0 files considered expired, 5 files considered live, 0 files are newer than max-file-modification-time.
2024-05-30 13:27:08,906 [ForkJoinPool-3-worker-1] INFO  o.p.g.expire.PerContentDeleteExpired - live-set#5f2cf659-2941-44e0-9642-9461b786d40c content#a1c70148-c8b2-4a52-8a05-f3f4378283f7: Found 43 total files in base location abfs://<REDACTED>@<REDACTED>.dfs.core.windows.net/iceberg/warehouse/raw_workflow_events_c48dca5b-271f-4a38-9841-1d49170ecf0d/, 0 files considered expired, 43 files considered live, 0 files are newer than max-file-modification-time.
2024-05-30 13:27:22,209 [ForkJoinPool-3-worker-3] INFO  o.p.g.expire.PerContentDeleteExpired - live-set#5f2cf659-2941-44e0-9642-9461b786d40c content#2a5db5b8-16b4-45d3-b627-7ebb03b71491: Found 85 total files in base location abfs://<REDACTED>@<REDACTED>.dfs.core.windows.net/iceberg/warehouse/x_events_25ca607a-0a26-4c36-bb03-09850ebd0331/, 0 files considered expired, 85 files considered live, 0 files are newer than max-file-modification-time.
2024-05-30 13:27:22,211 [main] INFO  o.p.g.e.local.DefaultLocalExpire - live-set#5f2cf659-2941-44e0-9642-9461b786d40c: Expiry finished, took PT42.185851937S, deletion summary: DeleteSummary{deleted=0, failures=0}.
Nessie-GC sweep phase for live-content-set 5f2cf659-2941-44e0-9642-9461b786d40c finished with status EXPIRY_SUCCESS after PT3.404244S, deleted 0 files, 0 files could not be deleted.
```
