### ISSUE TITLE
Fix root cause of flaky `TestCacheInvalidationSender#sendSingleInvalidation`

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#8819]
### Issue description

```
java.lang.AssertionError: 	
Expecting	
  <CompletableFuture[Failed with the following stack trace:	
io.vertx.core.impl.NoStackTraceTimeoutException: Timeout 10000 (ms) fired	
]>	
to be completed within 30L Seconds.	
exception caught while trying to get the future result: java.util.concurrent.ExecutionException: io.vertx.core.impl.NoStackTraceTimeoutException: Timeout 10000 (ms) fired	
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)	
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)	
	at org.assertj.core.internal.Futures.assertSucceededWithin(Futures.java:100)	
	at org.assertj.core.api.AbstractCompletableFutureAssert.internalSucceedsWithin(AbstractCompletableFutureAssert.java:443)	
	at org.assertj.core.api.AbstractCompletableFutureAssert.succeedsWithin(AbstractCompletableFutureAssert.java:439)	
	at org.assertj.core.api.CompletableFutureAssert$ByteBuddy$eqMvcBUu.succeedsWithin$accessor$TYK47KPV(Unknown Source)	
	at org.assertj.core.api.CompletableFutureAssert$ByteBuddy$eqMvcBUu$AssertJ$SoftProxies$0QtOCwcY.call(Unknown Source)	
	at org.assertj.core.api.ProxifyMethodChangingTheObjectUnderTest.intercept(ProxifyMethodChangingTheObjectUnderTest.java:79)	
	at org.assertj.core.api.CompletableFutureAssert$ByteBuddy$eqMvcBUu.succeedsWithin(Unknown Source)	
	at org.projectnessie.quarkus.providers.storage.TestCacheInvalidationSender.sendSingleInvalidation(TestCacheInvalidationSender.java:403)	
```

The following part is likely from a _different_ test...

```
Failed to resolve service names [serviceName] for remote cache invalidations
Failed to resolve service names [serviceName] for remote cache invalidations
Failed to resolve service names [serviceName] for remote cache invalidations
Failed to resolve service names [serviceName] for remote cache invalidations
Failed to resolve service names [serviceName] for remote cache invalidations
Failed to resolve service names [serviceName] for remote cache invalidations
Failed to resolve service names [serviceName] for remote cache invalidations
Failed to resolve service names [serviceName] for remote cache invalidations
Technical failure sending cache invalidations to 127.0.0.1:34185/foo/bar/?sender=senderId
```

**Comment by snazy** [comment]
Haven't seen this test failing for a while, closing
