### ISSUE TITLE
Test failure: testAuthorizedDeviceCode() FAILED :nessie-quarkus:test  org.projectnessie.server.TestOAuth2Authentication

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#8832]
Sample [run](https://github.com/projectnessie/nessie/actions/runs/9510459678/job/26214987357) in the `Exercise Java version (21)` job:
```
org.projectnessie.client.http.HttpClientException: OAuth2 server replied with HTTP status code: 404	
at org.projectnessie.client.auth.oauth2.OAuth2ClientConfig.genericError(OAuth2ClientConfig.java:307)	
at org.projectnessie.client.auth.oauth2.OAuth2ClientConfig.checkErrorResponse(OAuth2ClientConfig.java:286)	
at org.projectnessie.client.http.impl.jdk11.JavaRequest.lambda$executeRequest$1(JavaRequest.java:145)	
at java.util.Collections$SingletonList.forEach(Collections.java:5186)	
at org.projectnessie.client.http.impl.jdk11.JavaRequest.executeRequest(JavaRequest.java:145)	
at org.projectnessie.client.http.HttpRequest.post(HttpRequest.java:116)	
at org.projectnessie.client.http.HttpRequest.postForm(HttpRequest.java:131)	
at org.projectnessie.client.auth.oauth2.AbstractFlow.invokeEndpoint(AbstractFlow.java:102)	
at org.projectnessie.client.auth.oauth2.AbstractFlow.invokeTokenEndpoint(AbstractFlow.java:60)	
at org.projectnessie.client.auth.oauth2.DeviceCodeFlow.pollForNewTokens(DeviceCodeFlow.java:156)	
at org.projectnessie.client.auth.oauth2.DeviceCodeFlow.lambda$fetchNewTokens$0(DeviceCodeFlow.java:106)	
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)	
at java.util.concurrent.FutureTask.run(FutureTask.java:317)	
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)	
at java.lang.Thread.run(Thread.java:1583)
```

Output:
```

[nessie-oauth2-client] ======= Nessie authentication required =======
[nessie-oauth2-client] Browse to the following URL:
[nessie-oauth2-client] http://localhost:43697/auth/realms/quarkus/device
[nessie-oauth2-client] And enter the code:
[nessie-oauth2-client] CAFE-BABE
[nessie-oauth2-client] (The code will expire in 10 minutes)

2024-06-14 04:26:32,701 INFO  [org.pro.cli.aut.oau.KeycloakDeviceCodeResourceOwnerEmulator] (KeycloakDeviceCodeResourceOwnerEmulator4) Starting device code flow.
2024-06-14 04:26:32,701 INFO  [org.pro.cli.aut.oau.KeycloakDeviceCodeResourceOwnerEmulator] (KeycloakDeviceCodeResourceOwnerEmulator4) Entering user code...
2024-06-14 04:26:32,707 INFO  [org.pro.cli.aut.oau.KeycloakDeviceCodeResourceOwnerEmulator] (KeycloakDeviceCodeResourceOwnerEmulator4) Device code flow completed.
2024-06-14 04:26:32,728 INFO  [io.qua.htt.access-log] (executor-thread-1) 127.0.0.1 - alice [14/Jun/2024:04:26:32 +0000] "GET /api/v2/config HTTP/1.1" 200 374

[nessie-oauth2-client] ======= Nessie authentication required =======
[nessie-oauth2-client] Browse to the following URL:
[nessie-oauth2-client] http://localhost:43697/auth/realms/quarkus/device
[nessie-oauth2-client] And enter the code:
[nessie-oauth2-client] CAFE-BABE
[nessie-oauth2-client] (The code will expire in 10 minutes)

2024-06-14 04:26:32,740 INFO  [org.pro.cli.aut.oau.KeycloakDeviceCodeResourceOwnerEmulator] (KeycloakDeviceCodeResourceOwnerEmulator4) Starting device code flow.
2024-06-14 04:26:32,740 INFO  [org.pro.cli.aut.oau.KeycloakDeviceCodeResourceOwnerEmulator] (KeycloakDeviceCodeResourceOwnerEmulator4) Entering user code...
2024-06-14 04:26:32,745 INFO  [org.pro.cli.aut.oau.KeycloakDeviceCodeResourceOwnerEmulator] (KeycloakDeviceCodeResourceOwnerEmulator4) Device code flow completed.
2024-06-14 04:26:32,819 ERROR [org.pro.cli.aut.oau.DeviceCodeFlow] (nessie-oauth2-client-weeE-token-refresh-1) Authentication failed: OAuth2 server replied with HTTP status code: 404
2024-06-14 04:26:32,820 WARN  [org.pro.cli.aut.oau.OAuth2Client] (nessie-oauth2-client-weeE-token-refresh-1) Failed to fetch new tokens: org.projectnessie.client.http.HttpClientException: OAuth2 server replied with HTTP status code: 404
```

/cc @adutra

**Comment by adutra** [comment]
I've seen this failure a few times indeed. What is puzzling is that the error is a 404, which makes no sense since we are contacting the token endpoint. I wonder if the auth server isn't shutting down when it happens.

I suggest that we add more context to the exception such as the requested URI and maybe also the response body, if available.

**Comment by snazy** [comment]
[Here's one failure](https://scans.gradle.com/s/d2d4rintnm47s/tests/task/:nessie-quarkus:test/details/org.projectnessie.server.TestOAuth2Authentication/testAuthorizedDeviceCode()?expanded-stacktrace=WyIwIl0&top-execution=1):
```

[nessie-oauth2-client] ======= Nessie authentication required =======
[nessie-oauth2-client] Browse to the following URL:
[nessie-oauth2-client] http://localhost:39941/auth/realms/quarkus/device
[nessie-oauth2-client] And enter the code:
[nessie-oauth2-client] CAFE-BABE
[nessie-oauth2-client] (The code will expire in 10 minutes)

2024-06-20 04:24:17,178 INFO  [org.pro.cli.aut.oau.KeycloakDeviceCodeResourceOwnerEmulator] (KeycloakDeviceCodeResourceOwnerEmulator4) Starting device code flow.
2024-06-20 04:24:17,179 INFO  [org.pro.cli.aut.oau.KeycloakDeviceCodeResourceOwnerEmulator] (KeycloakDeviceCodeResourceOwnerEmulator4) Entering user code...
2024-06-20 04:24:17,186 INFO  [org.pro.cli.aut.oau.KeycloakDeviceCodeResourceOwnerEmulator] (KeycloakDeviceCodeResourceOwnerEmulator4) Device code flow completed.
2024-06-20 04:24:17,207 INFO  [io.qua.htt.access-log] (executor-thread-1) 127.0.0.1 - alice [20/Jun/2024:04:24:17 +0000] "GET /api/v2/config HTTP/1.1" 200 374

[nessie-oauth2-client] ======= Nessie authentication required =======
[nessie-oauth2-client] Browse to the following URL:
[nessie-oauth2-client] http://localhost:39941/auth/realms/quarkus/device
[nessie-oauth2-client] And enter the code:
[nessie-oauth2-client] CAFE-BABE
[nessie-oauth2-client] (The code will expire in 10 minutes)

2024-06-20 04:24:17,237 INFO  [org.pro.cli.aut.oau.KeycloakDeviceCodeResourceOwnerEmulator] (KeycloakDeviceCodeResourceOwnerEmulator4) Starting device code flow.
2024-06-20 04:24:17,237 INFO  [org.pro.cli.aut.oau.KeycloakDeviceCodeResourceOwnerEmulator] (KeycloakDeviceCodeResourceOwnerEmulator4) Entering user code...
2024-06-20 04:24:17,241 INFO  [org.pro.cli.aut.oau.KeycloakDeviceCodeResourceOwnerEmulator] (KeycloakDeviceCodeResourceOwnerEmulator4) Device code flow completed.
2024-06-20 04:24:17,309 ERROR [org.pro.cli.aut.oau.DeviceCodeFlow] (nessie-oauth2-client-6J1M-token-refresh-1) Authentication failed: Request to http://localhost:39941/auth/realms/quarkus/token failed with HTTP/404 and unparseable response body: 
                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
POST                                                       | POST
/auth/realms/quarkus/token                                 | /auth/realms/quarkus/token
                                                           |
Authorization: Basic cXVhcmt1cy1zZXJ2aWNlLWFwcDpzZWNyZXQ=  | Authorization: Basic cXVhcmt1cy1zZXJ2aWNlLWFwcDpzZWNyZXQ=
                                                           |
[contains]                                                 | grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ade<<<<< Body does not match
authorization_code                                         | vice_code&scope=scope1+scope2&device_code=1234&grantType=
                                                           | urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code
[contains]                                                 | grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ade<<<<< Body does not match
redirect_uri                                               | vice_code&scope=scope1+scope2&device_code=1234&grantType=
                                                           | urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code
                                                           |
-----------------------------------------------------------------------------------------------------------------------

2024-06-20 04:24:17,310 WARN  [org.pro.cli.aut.oau.OAuth2Client] (nessie-oauth2-client-6J1M-token-refresh-1) Failed to fetch new tokens: org.projectnessie.client.http.HttpClientResponseException: Request to http://localhost:39941/auth/realms/quarkus/token failed with HTTP/404 and unparseable response body: 
                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
POST                                                       | POST
/auth/realms/quarkus/token                                 | /auth/realms/quarkus/token
                                                           |
Authorization: Basic cXVhcmt1cy1zZXJ2aWNlLWFwcDpzZWNyZXQ=  | Authorization: Basic cXVhcmt1cy1zZXJ2aWNlLWFwcDpzZWNyZXQ=
                                                           |
[contains]                                                 | grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ade<<<<< Body does not match
authorization_code                                         | vice_code&scope=scope1+scope2&device_code=1234&grantType=
                                                           | urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code
[contains]                                                 | grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ade<<<<< Body does not match
redirect_uri                                               | vice_code&scope=scope1+scope2&device_code=1234&grantType=
                                                           | urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code
                                                           |
-----------------------------------------------------------------------------------------------------------------------
```
