### ISSUE TITLE
Unable to run Iceberg snapshot procedure using Nessie as REST catalog

### ISSUE THREAD

**Issue by rohanag12** [projectnessie/nessie#9999]
I'll preface this by mentioning that I'm not sure if this is an issue with nessie, iceberg, spark or PEBKAC. I'd like help figuring out which component is at fault here so I can file a bug report for the relevant project.

I'm trying to run the [iceberg snapshot procedure](https://iceberg.apache.org/docs/nightly/spark-procedures/#snapshot) on a Hive table. Spark makes 2 calls to the REST catalog - a create-table request to "stage" the table, and then an update-table request to commit the final result. The second call to update-table fails.

<details>

<summary>Relevant logs from spark/iceberg (click to expand):</summary>

```
24/11/27 17:18:13 INFO SnapshotTableSparkAction: Staging a new Iceberg table iceberg_db.iceberg_table as a snapshot of hive_db.hive_table
...
24/11/27 17:18:13 INFO SnapshotTableSparkAction: Ensuring iceberg_db.iceberg_table has a valid name mapping
24/11/27 17:18:13 INFO SnapshotTableSparkAction: Generating Iceberg metadata for iceberg_db.iceberg_table in s3://nessie-warehouse/iceberg_db/iceberg_table_47175d8a-fee7-4b6b-9bee-4a71b079864c/metadata
...
24/11/27 17:19:22 INFO SnapshotProducer: Committed snapshot 8069393551715768226 (MergeAppend)
24/11/27 17:19:22 INFO LoggingMetricsReporter: Received metrics report: CommitReport{tableName=iceberg.iceberg_db.iceberg_table, snapshotId=8069393551715768226, sequenceNumber=1, operation=append, commitMetrics=CommitMetricsResult{totalDuration=TimerResult{timeUnit=NANOSECONDS, totalDuration=PT0.803725073S, count=1}, attempts=CounterResult{unit=COUNT, value=1}, addedDataFiles=CounterResult{unit=COUNT, value=1200}, removedDataFiles=null, totalDataFiles=CounterResult{unit=COUNT, value=1200}, addedDeleteFiles=null, addedEqualityDeleteFiles=null, addedPositionalDeleteFiles=null, removedDeleteFiles=null, removedEqualityDeleteFiles=null, removedPositionalDeleteFiles=null, totalDeleteFiles=CounterResult{unit=COUNT, value=0}, addedRecords=CounterResult{unit=COUNT, value=8459573}, removedRecords=null, totalRecords=CounterResult{unit=COUNT, value=8459573}, addedFilesSizeInBytes=null, removedFilesSizeInBytes=null, totalFilesSizeInBytes=CounterResult{unit=BYTES, value=0}, addedPositionalDeletes=null, removedPositionalDeletes=null, totalPositionalDeletes=CounterResult{unit=COUNT, value=0}, addedEqualityDeletes=null, removedEqualityDeletes=null, totalEqualityDeletes=CounterResult{unit=COUNT, value=0}}, metadata={engine-version=3.5.1, app-id=spark-f10673a0006f4cd7bb6212718b431f5f, engine-name=spark, iceberg-version=Apache Iceberg 1.7.0 (commit 5f7c992ca673bf41df1d37543b24d646c24568a9)}}
24/11/27 17:19:22 INFO SnapshotTableSparkAction: Committing staged changes to iceberg_db.iceberg_table
24/11/27 17:19:22 ERROR SnapshotTableSparkAction: Error when populating the staged table with metadata, aborting changes
...
IllegalArgumentException: Found multiple updates of type SetProperties

JVM stacktrace:
java.lang.IllegalArgumentException: Found multiple updates of type SetProperties
	at org.apache.iceberg.rest.ErrorHandlers$DefaultErrorHandler.accept(ErrorHandlers.java:206)
	at org.apache.iceberg.rest.ErrorHandlers$TableErrorHandler.accept(ErrorHandlers.java:118)
	at org.apache.iceberg.rest.ErrorHandlers$TableErrorHandler.accept(ErrorHandlers.java:102)
	at org.apache.iceberg.rest.HTTPClient.throwFailure(HTTPClient.java:211)
	at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:323)
	at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:262)
	at org.apache.iceberg.rest.HTTPClient.post(HTTPClient.java:368)
	at org.apache.iceberg.rest.RESTClient.post(RESTClient.java:112)
	at org.apache.iceberg.rest.RESTTableOperations.commit(RESTTableOperations.java:159)
	at org.apache.iceberg.BaseTransaction.commitCreateTransaction(BaseTransaction.java:327)
	at org.apache.iceberg.BaseTransaction.commitTransaction(BaseTransaction.java:306)
	at org.apache.iceberg.spark.source.StagedSparkTable.commitStagedChanges(StagedSparkTable.java:34)
	at org.apache.iceberg.spark.actions.SnapshotTableSparkAction.doExecute(SnapshotTableSparkAction.java:141)
	at org.apache.iceberg.spark.JobGroupUtils.withJobGroupInfo(JobGroupUtils.java:59)
	at org.apache.iceberg.spark.JobGroupUtils.withJobGroupInfo(JobGroupUtils.java:51)
	at org.apache.iceberg.spark.actions.BaseSparkAction.withJobGroupInfo(BaseSparkAction.java:130)
	at org.apache.iceberg.spark.actions.SnapshotTableSparkAction.execute(SnapshotTableSparkAction.java:113)
	at org.apache.iceberg.spark.actions.SnapshotTableSparkAction.execute(SnapshotTableSparkAction.java:50)
	at org.apache.iceberg.spark.procedures.SnapshotTableProcedure.call(SnapshotTableProcedure.java:112)
	at org.apache.spark.sql.execution.datasources.v2.CallExec.run(CallExec.scala:34)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
	...
```
</details>

When the snapshot procedure runs, Nessie logs show the following (first call to create table returns status code 200, the second one fails with 400).

<details>

<summary>Relevant logs from nessie (click to expand):</summary>

```
2024-11-27 17:18:13,876 INFO  [io.qua.htt.access-log] (executor-thread-407) 172.16.178.111 - - [27/Nov/2024:17:18:13 +0000] "POST /iceberg/v1/main/namespaces/iceberg_db/tables HTTP/1.1" 200 4345
2024-11-27 17:19:22,896 INFO  [org.pro.cat.ser.res.IcebergErrorMapper] (executor-thread-407) Propagating storage failure to client: BackendErrorStatus{statusCode=BAD_REQUEST, cause=java.lang.IllegalArgumentException: Found multiple updates of type SetProperties}: java.lang.IllegalArgumentException: Found multiple updates of type SetProperties
        at org.projectnessie.catalog.formats.iceberg.rest.IcebergCatalogOperation.lambda$getSingleUpdate$1(IcebergCatalogOperation.java:95)
        at java.base/java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
        at org.projectnessie.catalog.formats.iceberg.rest.IcebergCatalogOperation.getSingleUpdate(IcebergCatalogOperation.java:92)
        at org.projectnessie.catalog.formats.iceberg.rest.IcebergCatalogOperation.getSingleUpdateValue(IcebergCatalogOperation.java:77)
        at org.projectnessie.catalog.service.impl.CatalogServiceImpl.pruneUpdates(CatalogServiceImpl.java:782)
        at org.projectnessie.catalog.service.impl.CatalogServiceImpl.lambda$applyIcebergTableCommitOperation$12(CatalogServiceImpl.java:672)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
        at java.base/java.util.concurrent.CompletableFuture$MinimalStage.thenApply(CompletableFuture.java:2948)
        at org.projectnessie.catalog.service.impl.CatalogServiceImpl.applyIcebergTableCommitOperation(CatalogServiceImpl.java:657)
        at org.projectnessie.catalog.service.impl.CatalogServiceImpl.commit(CatalogServiceImpl.java:509)
        at org.projectnessie.catalog.service.impl.CatalogServiceImpl.commit(CatalogServiceImpl.java:589)
        at org.projectnessie.catalog.service.impl.CatalogServiceImpl_ClientProxy.commit(Unknown Source)
        at org.projectnessie.catalog.service.rest.IcebergApiV1ResourceBase.createOrUpdateEntity(IcebergApiV1ResourceBase.java:435)
        at org.projectnessie.catalog.service.rest.IcebergApiV1TableResource.updateTable(IcebergApiV1TableResource.java:630)
        at org.projectnessie.catalog.service.rest.IcebergApiV1TableResource_Subclass.updateTable$$superforward(Unknown Source)
        at org.projectnessie.catalog.service.rest.IcebergApiV1TableResource_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:71)
        at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor.validateMethodInvocation(ResteasyReactiveEndPointValidationInterceptor.java:21)
        at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at org.projectnessie.catalog.service.rest.IcebergApiV1TableResource_Subclass.updateTable(Unknown Source)
        at org.projectnessie.catalog.service.rest.IcebergApiV1TableResource_ClientProxy.updateTable(Unknown Source)
        at org.projectnessie.catalog.service.rest.IcebergApiV1TableResource$quarkusrestinvoker$updateTable_c34993220e777c9c3636a8fdd6e5dacfbe77fe87.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:627)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)

2024-11-27 17:19:22,899 INFO  [io.qua.htt.access-log] (executor-thread-407) 10.238.186.43 - - [27/Nov/2024:17:19:22 +0000] "POST /iceberg/v1/main/namespaces/iceberg_db/tables/iceberg_table HTTP/1.1" 400 143
```
</details>

The relevant part is `java.lang.IllegalArgumentException: Found multiple updates of type SetProperties`. I captured the request body for the update-table request, and I can see that there are indeed 2 entires for SetProperties:

<details>

<summary>Multiple SetProperties entries (click to expand)</summary>

```
SetProperties{updates={nessie.staged=true, created-at=2024-11-27T17:18:12.378109647Z, parquet.compression=SNAPPY, classification=parquet, gc.enabled=false, snapshot=true}}

SetProperties{updates={schema.name-mapping.default=[ {
  "field-id" : 1,
  "names" : [ "redacted1" ]
}, {
  "field-id" : 2,
  "names" : [ "redacted2" ]
}, {
  "field-id" : 3,
  "names" : [ "redacted3" ]
}, {
  "field-id" : 4,
  "names" : [ "redacted4" ]
}, {
  "field-id" : 5,
  "names" : [ "redacted5" ]
}, {
  "field-id" : 6,
  "names" : [ "redacted6" ]
}, {
  "field-id" : 7,
  "names" : [ "redacted7" ]
}, {
  "field-id" : 8,
  "names" : [ "redacted8" ]
}, {
  "field-id" : 9,
  "names" : [ "redacted9" ]
}, {
  "field-id" : 10,
  "names" : [ "redacted10" ]
}, {
  "field-id" : 11,
  "names" : [ "redacted11" ]
}, {
  "field-id" : 12,
  "names" : [ "redacted12" ]
}, {
  "field-id" : 13,
  "names" : [ "redacted13" ]
}, {
  "field-id" : 14,
  "names" : [ "redacted14" ]
}, {
  "field-id" : 15,
  "names" : [ "redacted15" ]
}, {
  "field-id" : 16,
  "names" : [ "redacted16" ]
}, {
  "field-id" : 17,
  "names" : [ "redacted17" ]
} ]}}
```
</details>

So, my questions are:
* Why does spark/iceberg send 2 SetProperties entries in the update-table request, is that expected or a bug in iceberg/spark?
* In case this is not an iceberg/spark bug, why does nessie expect a single SetProperties entry, can it merge multiple entries instead?

My spark config:
```python
EXTENSIONS = ",".join([
    "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions",
    "org.projectnessie.spark.extensions.NessieSparkSessionExtensions",
])

SPARK_CONF = [
    ("spark.sql.extensions", EXTENSIONS),

    # session catalog
    ("spark.sql.catalog.spark_catalog", "org.apache.iceberg.spark.SparkSessionCatalog"),
    ("spark.sql.catalog.spark_catalog.type", "glue"),
    ("spark.sql.catalog.spark_catalog.io-impl", "org.apache.iceberg.aws.s3.S3FileIO"),

    # iceberg catalog
    ("spark.sql.catalog.iceberg", "org.apache.iceberg.spark.SparkCatalog"),
    ("spark.sql.catalog.iceberg.catalog-impl", "org.apache.iceberg.rest.RESTCatalog"),
    ("spark.sql.catalog.iceberg.uri", "https://nessie-url-redacted/iceberg"),
    ("spark.sql.catalog.iceberg.prefix", "main"),
]
```

Spark SQL:
```python
spark.sql("CALL iceberg.system.snapshot('hive_db.hive_table', 'iceberg_db.iceberg_table')")
```

**Comment by snazy** [comment]
It's strange that Iceberg sends more than one set-properties update, but it's not a big deal to allow that in Nessie.
